### ISSUE TITLE
Remove Role and Salary Expectations

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5118] opened 2022-12-14 20:21 UTC
## Description

Remove Role and Salary Expectations

## Considerations

How does this affect other sections of the platform?
Is this tied to tables? how do we uncouple it?
Any places where removing this will make something implode?

## Acceptance Criteria
- [ ] ...

**Comment by gobyrne** [comment] 2022-12-15 16:13
Duplicate of #5133

**Closed by gobyrne** 2022-12-15 16:13 UTC
