### ISSUE TITLE
🐛 `<Heading />` Component is not explicit in its styling props

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5790] opened 2023-02-23 13:13 UTC
## 🐛 Bug

The `<Heading />` component could be more explicit when selecting a size to display at.

## 🦋 Expected Behaviour

`<Heading />` component uses the size of the `level` defined unless it is overridden by `size`.

## 🕵️ Details

Currently, our `<Heading />` component defaults to `size = "h2"` which can cause some confusion when using different levels. We could have no default size and always fallback to the `level` prop and force developers to explicitly override it with the `size` prop.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Remove `size` default
- [ ] Ensure no visual diff

**Comment by mnigh** [comment] 2023-03-02 15:30
@esizer Possible duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/5790?

**Closed** 2023-03-13 17:42 UTC
Labels: interruption
