### ISSUE TITLE
Pool publish action fails without any user friendly error message when the deadline is already passed

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4179] opened 2022-10-03 18:38 UTC
User cannot publish a pool with deadline is already passed. Currently the pop up shows "Publish" button with the message "deadline is passed"  and when I click on it it fails without providing the reason.

![image (11).png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/7804599c-dbda-46ca-9a88-a390982a58c3
)

Post overhauling

Could be improved still 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/423a2ba8-a8de-458e-9c8e-c2a0967f769d)

### Acceptance Criteria

- [ ] When past the closing date and incomplete, Closing date no longer marked as all good

**Comment by gobyrne** [comment] 2022-10-03 19:36
Probably best if this shows up as an error message before the popup is displayed?
@Jerryescandon

**Comment by Jerryescandon** [comment] 2022-10-03 19:54
> Probably best if this shows up as an error message before the popup is displayed? @Jerryescandon

agree, probably best if the validation for this is done when clicking the button and show the error on the date field.

**Comment by petertgiles** [comment] 2023-01-19 19:43
Tricky to do form validation since publishing the pool is not a form submission.
Related: #3586

**Comment by mnigh** [comment] 2023-06-01 18:30
@Jerryescandon what about hiding the publish button altogether if the closing date is in the past?

## Screenshot
![Screen Shot 2023-06-01 at 14 27 52](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/bf1cc09e-6a3a-460f-9a64-e0b496eb3062)

**Comment by Jerryescandon** [comment] 2023-06-01 18:36
Mhhh it wouldn't solve the issue entirely since we would still not be communicating where the problem is. Maybe we can just rely on toast notifications to better inform the user why the "publish" action failed.

`Error: The closing date for this advertisement has passed.`

**Comment by mnigh** [comment] 2023-06-01 19:39
> Mhhh it wouldn't solve the issue entirely since we would still not be communicating where the problem is. Maybe we can just rely on toast notifications to better inform the user why the "publish" action failed.
> 
> `Error: The closing date for this advertisement has already passed.` or `Error: The deadline for this advertisement should be in the future.`

We can't because of what @petertgiles mentioned [here](https://github.com/GCTC-NTGC/gc-digital-talent/issues/4179#issuecomment-1397509357) and the fact that our `PoolPolicy` is doing the validation when it really shouldn't be.

**Comment by mnigh** [comment] 2023-06-01 21:05
Related #6802.

**Closed** 2023-12-06 15:09 UTC
Labels: bug
