### ISSUE TITLE
⌨ Closing talent request dialog shifts focus to start of page

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#11976] opened 2024-11-14 21:05 UTC
## ⌨ Accessibility Issue

On the manager dashboard, when closing a talent request dialog, the focus jumps back up to the top of the page unexpectedly.

## 🦋 Expected Behaviour

When closing the dialog, focus is returned to the trigger that invoked it.

## 📋 Steps to Reproduce

1. Login as manager `manager@test.com`
2. Navigate tot he dashboard `/manager/dashboard`
3. Using your keyboard, open a talent request dialog
4. Use the cancel button in the footer to close the dialog
5. Observe the focus shift to the start of the page instead of returning to the trigger

## ✅ Acceptance Criteria

- [ ] Focus returns to trigger when closing the dialog

**Comment by tristan-orourke** [comment] 2024-11-15 22:12
I think this is a duplicate of #11992.
@esizer please reopen this and move to Ready for Estimate if I'm wrong.

**Closed by tristan-orourke** 2024-11-15 22:12 UTC
Labels: accessibility
