### ISSUE TITLE
📐 Add the filter dialogue to the Request management table

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#6707] opened 2023-05-25 16:25 UTC
# ⚙️ Summary

### [Visit the Figma file](https://www.figma.com/file/UsrB15yicgDCLDQmx3snyl/User-Flows?type=design&node-id=0-1&t=qglX0KcmEUwWldEO-0)

@gobyrne, @Jerryescandon  san I met with the Recruitment and Tallent Acquisition Team to discuss referral service design considerations. This insight has been added to the tracker.  

## ✅ Design checklist

- [ ] Component library elements have been used where appropriate
- [ ] Component library elements have been updated where changes where required
- [ ] Newly added interface elements have been added to the component library for reuse
- [ ] Newly added interface elements have been added to Github Discussions using the component issue template
- [ ] The interface is responsive or provides responsive context
- [ ] The interface provides both light and dark mode designs
- [ ] Complex interactions have been prototypes in a way that showcases every step in the flow
- [ ] Empty/null states have been accounted for
- [ ] A [content spreadsheet](https://1drv.ms/x/s!Ajx0PiLIqEzSgclOERYCPtg3t9dKyQ?e=BBFKF1) has been created and copywriting has been assigned
- [ ] The design has been reviewed by at least one other team member
- [ ] The design has been presented to the design team
- [ ] The design has gone through at least one round of usability testing
- [ ] The design has gone through at least one round of accessibility testing
- [ ] The design has been approved by stakeholders

## ✅ Accessibility checklist

**Please refer to [the comprehensive list](https://www.figma.com/file/rRMvm5nq4AMet29PW7bN2p/A11y-annotations?node-id=0%3A1) for more details.**

- [ ]Headings are identified using annotations and follow a logical hierarchy
- [ ] Layout is linear and consistent with established patterns
- [ ] Navigation matches previously established patterns
- [ ] Tab order has been identified using annotations
- [ ] New interactive elements have appropriately sized touch targets on touch devices
- [ ] Links have meaningful and descriptive label text
- [ ] New interactive elements have unique focus states that match the established pattern
- [ ] Relevant images and icons have appropriate `alt` text, and it is not duplicative of the descriptive links/Header texts
- [ ] Use of color meets  WCAG  AA contrast requirements
- [ ] States, instructions or information are not conveyed by color alone

# ✅ Requirement

## 🛠️ Make Filter available on the Request Management Table  

Right now the "fancy filter" filter dialog is closely coupled to the User model and it's properties. Let's create a new filter component based on the existing one that is fully generic. Ideally it could be used to filter tables of users, pool candidates, requests, or any other model.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/101275838/612ba08f-97c6-448a-9614-b1274a16a469)

# 🤔 Outstanding concerns

Currently, recruitment team members must navigate inside a manager request from the request management table before they can modify any filters. Allowing the team to create its own request using the filters from the **_request management interface (table)_** **would eliminate the need for them to navigate away from the table** to the inside of a particular request or to the **Users Table interface** to expand search request criteria. Thus, saving them time and realizing an efficiency. 

# 📝 Related issues

**Please link all design and development sub-tasks related to this issue here for tracking purposes.**

- #3973 
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6365

**Comment by Jerryescandon** [comment] 2023-05-25 18:09
Related to https://github.com/GCTC-NTGC/gc-digital-talent/issues/6365

**Comment by tristan-orourke** [comment] 2023-06-06 18:41
Duplicate of #6365

**Closed by tristan-orourke** 2023-06-06 18:41 UTC
Labels: debt, accessibility
