### ISSUE TITLE
🐛 Application profile edit this information leads to error page

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#8098] opened 2023-09-29 13:14 UTC
## 🐛 Bug

Under the profile, when a user is clicking on Edit this information, they are led to an error page instead of the editing page.

## 🦋 Expected Behaviour

They should be led to the editing page.

## 🕵️ Details
Some users also get an error message when attempting to review their application profile. Here are some URLs and more details:
https://talent.canada.ca/en/applications/1be817bd-db48-436f-b4b1-0a74f1a9bacd

I click on the big purple button Let's go I get a banner that goes away quickly "Action not authorized" and a new purple button is displayed https://talent.canada.ca/en/applications/1be817bd-db48-436f-b4b1-0a74f1a9bacd/welcome "Return to the last step I was working on"

## 📸 Screenshot
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/42844328/5aa099b2-1dec-4360-9e26-c510dde2ccea)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/42844328/47f404e0-ada8-4b99-8a30-7772875f3c4b)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/42844328/6e395b7e-cd53-42bf-8bb8-29bc13d7609e)

## Steps to reproduce 
1. Apply for a pool 
2. Application should be either "Application received" or "Pending Assessment" status
3. Make the pool as expired
4. Now go to the profile & applications page and click Review Application link on the application card
5. Observe you got to the application stepper page with "Welcome" 
6. Click on "Lets go" button 
7. Observe the error mentioned in the screen shot / video 

Review application calls
UpdateAppliation mutation and it errors out as “This action is unauthorized”

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] User should be able to view his own application in read only mode when the pool is expired

**Comment by tristan-orourke** [comment] 2023-09-29 14:27
Off the top of my head, my guess is something went wrong with the `submittedSteps` field?

**Comment by brindasasi** [comment] 2023-09-29 16:26
I’m able to re-produce it in UAT.
User get this error when trying to view his own application when the pool is expired.

**Comment by petertgiles** [comment] 2023-10-03 20:07
@marc-donofrio - can you confirm?  Was the original user interacting with an expired pool?

**Comment by petertgiles** [comment] 2023-10-05 14:57
For a quick solution should we just do a check for an expired pool and toast an error indicating that?

**Comment by brindasasi** [comment] 2023-11-03 13:03
@marc-donofrio is this still an issue ? I couldn't reproduce this in UAT any more.

**Comment by gobyrne** [comment] 2024-01-04 15:45
I am not able to re-produce anymore either. Closing

**Closed by gobyrne** 2024-01-04 15:45 UTC
Labels: bug, blocked: design
