### ISSUE TITLE
My Skills - Skill Results Component

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#1543] opened 2021-12-23 19:47 UTC
# Description
This component is a list of items, each shows a skill name, a Expand/Hide definition button that expands/hides the skill description, and a Add/Remove skill button to the right.

The component needs to receive a list of skills to show, a list of skills already associated with the user (to determine whether to show the add or remove button), and Add and Remove handler functions.

Don't worry about pagination for this story.

You can see the Results component under the Add Skills section of the Experience form.
[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)

# Definition of Done

- [ ] Shows number of result items at top of component
- [ ] Show/hide description button works
- [ ] Add/remove button calls handler functions
- [ ] Skills appear differently if they're already added or not
- [ ] Jest tests that confirm the above facts
- [ ] Story in storybook shows this component

**Comment by tristan-orourke** [comment] 2022-01-11 20:03
A duplicate of #1482

**Closed by tristan-orourke** 2022-01-11 20:03 UTC
Labels: feature
