### ISSUE TITLE
♻️ Dead Code - Remove User.jobLookingStatus and all references to it

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5737] opened 2023-02-16 21:20 UTC
## ♻️ Debt/Refactor

Once users can opt out of searches on a per-application basis, the jobLookingStatus is redundant. And it's confusing! So lets get rid of it, backend and frontend.

## 🕵️ Details

jobLookingStatus no longer exists in the schema, in the database, in any models or seeders. References to it do not exist in model scopes or query resolvers or mutations. 

We also remove all reference to it on the frontend. At this point, those should only remain on the admin side as a User filter.

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] jobLookingStatus no longer exists in the schema, in the database, in any models or seeders
- [ ] references to jobLookingStatus do not exist in model scopes or query resolvers or mutations, or phpunit tests, or anywhere else in backend code
- [ ] any UI which references jobLookingStatus is removed
- [ ] no frontend code or graphql operations remain which reference jobLookingStatus.

**Comment by vd1992** [comment] 2023-08-02 22:48
Duplicate of issue in review #6985

**Closed by vd1992** 2023-08-02 22:48 UTC
Labels: debt
