### ISSUE TITLE
⚙️ Dashboard cards with coloured headers

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11027] opened 2024-07-22 14:51 UTC
## ⚙️ Summary

A reusable component, specific to the dashboards, with consistent styling which wraps different chunks of functionality on the dashboards.

## 🎨 Design File

[Include a link to the design file (if it exists).](https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=1010-18639&t=j4U5JEvsDbOlCAf0-0)

### 🧑‍🎨 Designer

@substrae 

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

### ✅ Design checklist

- [ ] Default component
- [ ] Dark mode component
- [ ] Component variants
- [ ] Dark mode component variants (if applicable)
- [ ] Foundational design info (e.g. color info, icons, helpful values)
- [ ] Mobile (`base` query) layout and space diagram
- [ ] Desktop (`p-tablet` query or larger) layout and space diagram
- [ ] Accessibility considerations
- [ ] Hover states (if applicable)
- [ ] Dark mode hover states (if applicable)
- [ ] Focus states (if applicable)
- [ ] Dark mode focus states (if applicable)

### ✅ Accessibility checklist

- [ ] Tap targets are adequate on smaller screens
- [ ] Color contrast for all modes and states has been checked and cleared
- [ ] Zoom has been considered as layout changes occur
- [ ] `alt` text has been identified and labelled
- [ ] Non-standard states or interactions have been described and provided accessible design context

## 🛠️ Properties

The card is shadowed, with 10px radius borders.

The header child element should be surrounded by padding 1x, 1.5x, 1x, 1.5x

### Header colour
One of a set of light colours - the `lightest` variant of `primary`, `secondary`, `tertiary`, `quartenary` and `quinary` colours.

### Header child
Any element or component. Fills the coloured header section.

### Content child
Any element or component. Appears below the header on the card.

## Screenshot

![image](https://github.com/user-attachments/assets/960ff9d8-cad4-4de8-aefb-d0eea52798c9)

## 💡 Interaction states

None

### Accessibility feature name

Feature description.

**Comment by yonikid15** [comment] 2024-08-08 18:44
Duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/11075 TaskCard component

**Closed by yonikid15** 2024-08-08 18:44 UTC
