### ISSUE TITLE
Admin sidemenu broken

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4792] opened 2022-11-17 15:33 UTC
I think we broke the admin sidemenu at some point.  If you click the close menu link the the text disappears but the width does not decrease.  And when the window becomes narrow enough the menu disappears but the "open menu" button is at the bottom of the page instead of floating.

https://user-images.githubusercontent.com/8978655/202489257-fb11cc90-7d7f-48f0-9c42-fc4b4efbedcf.mp4

**Comment by petertgiles** [comment] 2022-11-17 15:42
Actually, the open menu button is below the footer now.

**Comment by vd1992** [comment] 2022-11-17 16:16
duplicate of #4678

**Closed by vd1992** 2022-11-17 16:16 UTC
Labels: bug
