### ISSUE TITLE
Chromatic storybook needs to build all hydrogen.css files and add common.css

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#1977] opened 2022-02-03 16:39 UTC
# Description
It seems that the common.css file is not added during the chromatic storybook build. An example of this is the `.reset-ul` class not being applied to the Pagination component.
<img width="722" alt="Screen Shot 2022-01-31 at 8 30 14 PM" src="https://user-images.githubusercontent.com/305339/151899995-0e57db22-f6bd-4bcc-907f-69a55d21c52b.png">

We suspect the issue is instead that admin/webpack.mix.js has some config that is not properly mirrored in admin/.storybook/main.js, particularly related to CSS.

**Comment by patcon** [comment] 2022-02-03 19:46
> [only the admin folders hydrogen.css file gets built](https://github.com/GCTC-NTGC/gc-digital-talent/blob/e177b9ded572cac86b29eeddc69c18ea4e16f5f1/.github/workflows/storybook.yml#L49-L69)

Hm. I recognize it's awkwardly unclear (which I agree is a code-smell, because legibility it important), but I think this bit might be a red herring?

To explain: I removed `npm run h2-build` from those non-admin dirs because the whole single merged storybook is only building based on config in `admin/.storybook/` and `admin/hydrogen.config.js`. And I believe these have already been adapted to generate from `common/` and `talentsearch/`. This was needed to allow a single storybook to be built.

For example, in `admin/hydrogen.config.js`, it already builds its `hydrogen.css` file from JS in all of `common/`, `talentsearch/` and `admin/`:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/1fa7c34531270c479f63f1494f36a6b3855e7e26/frontend/admin/hydrogen.config.json#L4-L8

I suspect the issue is instead that `admin/webpack.mix.js` has some config that is not properly mirrored in `admin/.storybook/main.js`, particularly related to CSS.

I'll sort it out and maybe try to dedup a bit between those two files' webpack configs. Maybe we can use a shared `webpack.config.js`, like done here: https://github.com/skore/laravel-tailwind-storybook/blob/main/webpack.mix.js

**Comment by patcon** [comment] 2022-02-03 19:50
To confirm, running this still shows the issue locally:

```
cd frontend/admin
MERGE_STORYBOOKS=true npm run storybook
```

**Comment by yonikid15** [comment] 2022-02-03 20:06
Oh my fault, I didn't see that `hydrogen.config.js` file in admin is now parsing all frontend folders. I'll remove that from the description. As for the `common.css` file, I believe you are correct:

> I suspect the issue is instead that admin/webpack.mix.js has some config that is not properly mirrored in admin/.storybook/main.js, particularly related to CSS.

I can tackle this if you want no big deal. I can make quick fix to add the common.css file. As for using a shared `webpack.config.js` file, maybe we can break that out into a new issue? Unless you're already working both 😆

**Comment by patcon** [comment] 2022-02-04 03:32
☝️ ☝️ ☝️ 

Sorry, was slow on my 👍  reply. When I realized y'all were out for the day, figured I'd just submit so it's a quick fix in the morning :)

**Closed** 2022-03-08 22:05 UTC
Labels: bug
