### ISSUE TITLE
🐛 New accordions look odd in `OngoingRecruitmentSection`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5623] opened 2023-02-06 21:34 UTC
## 🐛 Bug

After updating the styles for the `Accordion` component, they look a little off in the `OngoingRecruitmentSection`.

## 🦋 Expected Behaviour

The accordions should appear as they do in the [storybook](https://www.chromatic.com/component?appId=61e099a1bb1465003a73d3ce&csfId=components-accordion&buildNumber=4299&k=63e16210811e7e04c7329486-1200-interactive-true&h=5&b=-1).

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Windows 11
- **Browser**: Chrome 109

## 📋 Steps to Reproduce

1. Navigate to  `/browse/pools`
2. Scroll to the "Apply to ongoing recruitment"
3. Notice the accordion styles

## 📸 Screenshot

![Screenshot 2023-02-06 162732](https://user-images.githubusercontent.com/4127998/217092491-d95a3c33-9047-43f5-b3fd-0768d37d30e6.png)

## 🙋‍♀️ Proposed Solution

I believe it could be related to the removal of margin and padding on the root.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/57b0dc68b93db0d3aacd4ac62048d1a7322ff107/apps/web/src/pages/Pools/BrowsePoolsPage/components/OngoingRecruitmentSection/OngoingRecruitmentSection.tsx#L837-L841

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Accordions render properly in the "Ongoing Recruitments" section

**Comment by brindasasi** [comment] 2023-02-14 16:48
duplicate of #5620

**Closed by brindasasi** 2023-02-14 16:48 UTC
Labels: bug
