### ISSUE TITLE
Memory leak on profile -> salary edit

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3979] opened 2022-09-16 12:44 UTC
Steps to reproduce
1) Navigate to /talent/profile
1) Scroll to the Salary section
1) Click the edit link
1) Make a change and click "Save and go back"

Note: I think this only happens on the final edit when the "You can now activate your profile" toast is popped

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/b760816e-7546-4bd5-a909-146949c93834)

**Comment by vd1992** [comment] 2022-09-16 15:32
there appears to be a grouping of them now
#3740 
same root cause?

**Comment by petertgiles** [comment] 2022-09-16 17:01
> same root cause?

Yeah, I bet we're all seeing the same thing.

**Comment by gobyrne** [comment] 2022-09-29 19:40
@esizer thinks it's the scroll to top. We have a listener, but we don't close it. There's a scroll to component in React-Router we could use that might solve this.

**Comment by esizer** [comment] 2022-11-17 18:05
Closed by #4597

**Closed by esizer** 2022-11-17 18:05 UTC
Labels: bug
