### ISSUE TITLE
🐛 Unstable Story - AdminLayout

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10851] opened 2024-07-02 19:58 UTC
## 🐛 Bug

I often see false diffs on the AdminLayout stories as the theme switcher seems to move.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/40a4cab1-6c50-487f-be9d-355f4f0965f8)

## 🙋‍♀️ Proposed Solution

A similar PR might help:
https://github.com/GCTC-NTGC/gc-digital-talent/pull/5912

## ✅ Acceptance Criteria

- [ ] No false diffs on AdminLayout stories.

**Comment by mnigh** [comment] 2024-07-02 20:16
Duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/10343?

**Comment by petertgiles** [comment] 2024-07-02 20:18
> Duplicate of #10343?

Yeah, same issue.  That one has a PR and was closed so lets leave this one open.

**Closed** 2024-07-03 11:58 UTC
Labels: bug
