### ISSUE TITLE
Entire profile page reloads after changing any subsection

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4471] opened 2022-10-27 17:04 UTC
# Introduction

When one of the components on the profile page is edited the entire page reloads and user needs to find their spot again.  This is a bigger deal further down the page, like with skills.  This is probably occurring because the pending component swaps out the entire form to reload the User object when the save mutation is run.

Originally found as an issue on the DEI page:
https://recordit.co/M7Ph1AmhvB

# Desired Behaviour

When one of inline forms or controls has the save button saved the save button should disable itself while working.  When the save is successful the control should reload with fresh data but the rest of the page should not go into pending mode since it is unlikely something else has changed outside the subsection.

# Proposed solution

- Don't use pending for the entire page?
- Use several queries to separately populate each section instead of one big query?
- Use a "scroll-to" to go back to the same spot after the page reloads?

# Acceptance Criteria

- [ ] Page does not lose the user's spot after form submission
- [ ] Even better - the page does not reload after form submission

**Comment by esizer** [comment] 2022-10-28 17:41
Looks like this is occurring because we run the mutation on every change. I think the only way around this is to wrap all of the options in a single `FormProvider` and add a "Save changes" button at the bottom so we run the mutation once, after all changes have been made.

<img width="570" alt="Screenshot 2022-10-28 at 1 39 00 PM" src="https://user-images.githubusercontent.com/4127998/198699037-63600c65-3aab-4de7-89b6-82eda7434d86.png">
<img width="956" alt="Screenshot 2022-10-28 at 1 39 17 PM" src="https://user-images.githubusercontent.com/4127998/198699036-d97482dd-667e-408f-ab6b-945aa531e229.png">

**Comment by petertgiles** [comment] 2023-01-13 15:15
@gobyrne Other than the Indigenous identity work, are they any other design updates planned for this page than might make us push this off?

**Comment by mnigh** [comment] 2023-08-08 19:45
@esizer is this issue still relevant with the move to inline profile forms?

**Comment by esizer** [comment] 2023-08-08 20:31
> @esizer is this issue still relevant with the move to inline profile forms?

This is still happening, yes. Though, I'm not sure how we get around it 😢

**Comment by esizer** [comment] 2023-08-29 17:45
Now that we merged all profile forms into a single page it is actually happening for all of them. 

Are we okay with this behaviour or do we want to:

1. Rescope this ticket or,
2. Close and create a new ticket

**Comment by petertgiles** [comment] 2023-08-29 17:52
> Are we okay with this behaviour

I'll add to the refinement queue

**Comment by esizer** [comment] 2023-10-30 21:55
Fixed with the extraction of user auth info type. IF someone can confirm, I believe it will be safe to close.

**Comment by petertgiles** [comment] 2023-10-31 12:56
Confirmed - works great now.

**Closed by petertgiles** 2023-10-31 12:56 UTC
Labels: bug, debt
