### ISSUE TITLE
ApplicantFilterTest intermittently failing

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6101] opened 2023-03-28 19:33 UTC
## 🐛 Bug

The "filter can be stored and retrieved without changing results" test is intermittently failing

## 🦋 Expected Behaviour

The test should be reliably passing unless there's actually a bug

## 🕵️ Details

```
  ⨯ filter can be stored and retrieved without changing results          3.76s  

FAILED  Tests\Feature\ApplicantFilterTest > filter can be stored and retr…   
  Failed asserting that 2 matches expected 1.

  at tests/Feature/ApplicantFilterTest.php:533
    529▕             [
    530▕                 'where' => $retrievedFilter,
    531▕             ]
    532▕         );
  ➜ 533▕         $this->assertEquals($firstCount, $response->json('data.countApplicants'));
    534▕     }
    535▕ }
    536▕

  1   tests/Feature/ApplicantFilterTest.php:533

```

## 📋 Steps to Reproduce

1. Run Phpunit ApplicantFilterTest

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/c2b62f5a-748e-4e6d-880e-cd42d6961a0d)Add a screenshot (if possible).

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] The test should be reliably passing unless there's actually a bug

**Comment by tristan-orourke** [comment] 2023-05-18 17:21
Duplicate of #6439

**Closed by tristan-orourke** 2023-05-18 17:21 UTC
Labels: bug, tests
