### ISSUE TITLE
🐜 Accessibility Bug: Page loading information on return from GC Key

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5424] opened 2023-01-20 19:43 UTC
## ❌ Current behaviour (issue)
No info is given to the screen reader that the application profile page is loading after the GC Key Sign in/Sign up redirect.  
**WCAG 2.1 Criteria:**

## Reproduction info: 
1. Open VoiceOver, Narrator or NVDA
2. Navigate to the Browse Jobs page. 
3. Activate  **Apply to this recruitment**
4. On Job poster, activate **Apply to this process** 
5. Sign in to GC Key on the welcome page. 
6. Listen for loading information for the Application profile page. 
### Fable Video Clip:
Return to Application Profile after GC Key (https://app.makeitfable.com/share/63cae318a597030013974282) 
## ✔ Expected behaviour (fix)
Page information loads for screen reader 

### Acceptance Criteria
- [ ] Page loading feedback is delivered to screen readers.   

### Additional Information 
- This helps a screen reader user orient themselves in the platform when returning from GC Key without having to necessarily arrow through the page mystery.

**Comment by substrae** [comment] 2023-01-20 19:46
@RM-1978 The details here don't seem to align with the behaviour described (returning from GC Key vs. Citizenship component). Is it possible these are two separate issues?

**Comment by RM-1978** [comment] 2023-01-20 19:52
Indeed @substrae, that will teach me to try and multi-task :)

**Comment by gobyrne** [comment] 2023-01-20 21:17
Would this be handled more broadly by a "page loading" spinner component? I think we did one of those for Talent Cloud? @yonikid15

**Comment by petertgiles** [comment] 2023-01-25 17:51
Duplicate of  #4545.  Reopen if there's something unique to this issue.

**Closed by petertgiles** 2023-01-25 17:51 UTC
Labels: bug, duplicate, accessibility
