### ISSUE TITLE
✨ Rework all `Accordion` instance so it can accept open/closed trigger states

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6797] opened 2023-06-01 15:00 UTC
## ✨ Feature

@substrae wants our accordions to show different text on the trigger depending on if it's currently open or closed. This way it could shift between "Hide this content" and "Show this content"

## 🕵️ Details

I assume we want to be able to pass two different strings as props into a component. Also, possibly, two aria-labels for the different states.

The accordion should also announce their interactivity and current state to AT.

## 🙋‍♀️ Proposed Implementation

```tsx
const [value, setValue] = React.useState<string>("");

return (
  <Accordion.Root value={value} onValueChange={setValue}>
    <Accordion.Item value="one">
      <StandardAccordionHeader>
        {value === "one" ? "Open" : "Close"}
      </StanardAccordionHeader>
    </Accordion.Item>
    <Accordion.Item value="two">
      <StandardAccordionHeader>
        {value === "two" ? "Open" : "Close"}
      </StanardAccordionHeader>
    </Accordion.Item>
  </Accordion.Root>
);
```

## ✅ Acceptance Criteria

- [ ] accordions announce their interactivity and current state to Accessibility Tools
- [ ] when using accordions in our layouts, we can easily specify different text and aria labels for the trigger, depending on its state
- [ ] review with @substrae instances of show/hide copy

**Comment by esizer** [comment] 2023-08-17 20:26
How do we want to handle this when the title is dynamic? The casing and wording of some of these is a little odd 🤔 Also, it might not be the best bet to blanket prepend on all accordions, we may need some custom text written for each one to make it make sense.

![Screenshot 2023-08-17 162538](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/278c819a-0142-4c1f-bca1-845bca92611d)

![Screenshot 2023-08-17 162031](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/366213fe-c942-45f4-957a-7c6f9f828a43)

**Comment by tristan-orourke** [comment] 2023-08-21 14:43
Yeah, I'm tempted to block this on having specific copy for everywhere. @substrae, would you be willing to go through the app and give us specific open/closed copy for every place accordions appear?

**Comment by substrae** [comment] 2023-08-24 18:38
@esizer @tristan-orourke 

The functionality can be added without retroactively applying text no? Let's just apply existing text to both states for now, and new accordions will take advantage of the feature as needed.

**Comment by tristan-orourke** [comment] 2023-09-01 18:36
@substrae I think we decided that we can't implement this at the Accordion component level. It will have to implemented at the page level - each page that has accordions on it can track the state of the accordion and render different text accordingly (😉). So there isn't any point to doing any work here unless we have the texts ready to go.

@esizer do I have that right?

**Comment by substrae** [comment] 2023-09-01 18:42
@tristan-orourke @esizer 

Wheh? That doesn't make sense to me... Accordions already accept a title, so can we not just take existing titles and use them in both slots unless the new open/close strings are passed? If the instance of the component doesn't provide open/close data, use the existing title prop instead.

**Comment by esizer** [comment] 2023-09-01 19:14
> @tristan-orourke @esizer
> 
> Wheh? That doesn't make sense to me... Accordions already accept a title, so can we not just take existing titles and use them in both slots unless the new open/close strings are passed? If the instance of the component doesn't provide open/close data, use the existing title prop instead.

I may be wrong, but it sounds like you are both saying the same thing in different words. 😅 

So, you are right @substrae there is technically nothing stopping us from doing this immediately by just prepending the title with open/close. The problem is, we aren't taking into consideration the actual title by doing a "one size fits all" solution.

For a specific example, we have a skill that, in English, is named "Networking". It just so happens that "Open Networking" is a real skills people could also have (we just don't have it as a skill). So it seems confusing because the skill isn't "Open Networking", it is prompting you to open the details of the networking skill.

So for this, we would probably write "Open 'Networking' details" or something to be clear about the actual skill name.

That is what we are referring to when we mean that we need specific text for each set of accordions instead of just appending "open/close" to all.

**Comment by substrae** [comment] 2023-09-01 19:18
@esizer 

Hmm, so I don't think prepending open/close is a good idea anyway. What I'm suggesting is that an accordion can be provided with three different title props:
- A single title that shows for both the `open` and `close` state (this would be applied to all existing accordions so that we're not breaking things)
- A custom `open` state title
- A custom `closed` state title

The latter two need to be provided together, otherwise the single title can apply to both states. That way, for accordions where we do want custom open/close text, our grammar isn't limited by prepended text

**Comment by tristan-orourke** [comment] 2023-09-01 19:23
> - A custom open state title
> - A custom closed state title

That's where we run into trouble: the accordion itself doesn't "know" what state its in, so providing the accordion component open and closed text doesn't help.

**Comment by esizer** [comment] 2023-09-01 19:24
> Hmm, so I don't think prepending open/close is a good idea anyway. What I'm suggesting is that an accordion can be provided with three different title props:

Okay, so that is where the confusion lies. We don't have it done exactly like that but the functionality does exist and is already implemented on [experience cards](https://61e099a1bb1465003a73d3ce-rmslaogdvh.chromatic.com/?path=/story/components-experience-card--award-experience-card). I thought this was an issue to just do this for every other accordion on the site so we were looking for the exact text we wanted to use for each one 😅

**Comment by substrae** [comment] 2023-09-01 19:30
@tristan-orourke @esizer 

I'm now more confused 😂 

How can the accordion not be aware of its own state? There isn't a class or data-attribute that indicates whether it's open or not? If there is, we can use that + Hydrgoen to hide/show the correct title string. Easy peasy.

**Comment by esizer** [comment] 2023-09-01 19:42
> How can the accordion not be aware of its own state? There isn't a class or data-attribute that indicates whether it's open or not? If there is, we can use that + Hydrgoen to hide/show the correct title string. Easy peasy.

I think it is confusing because we [already can and are doing this](https://github.com/GCTC-NTGC/gc-digital-talent/issues/6797#issuecomment-1703226825), just in a different way than what you described.

We could just hide via css though, our current solution does the same thing but actually unmounts the component to reduce the DOM/CSS footprint. Also, if we are going to be deciding titles on a case by case situation it doesn't really reduce the amount of code we need to write either.

```tsx
// Current
<Accordion.Item value="two">
  <StandardAccordionHeader>
     {value === "two" ? "Open" : "Close"}
   </StanardAccordionHeader>
</Accordion.Item>

// With Props
<Accordion.Item value="two">
  <StandardAccordionHeader
     openTitle="Open"
     closedTitle="Closed"
  />
</Accordion.Item>
```

This ticket would be refactoring our current implementation for no real gain and a possible (very, very, minimal) performance hit.

**Comment by substrae** [comment] 2023-09-01 20:32
@esizer

Okay, so just so I'm 100% clear:
- The component already works the way I'm describing; we can either pass one universal title or separate open and close state titles
- You've already designed it to unmount (which IMO is preferable to CSS, I was just offering an easy solution)

Can this ticket just be closed then?

**Comment by esizer** [comment] 2023-10-24 21:03
> Can this ticket just be closed then?

Oops, I totally glanced at this and forgot to respond. Yeah, I think we can close this 👍

**Closed** 2023-10-25 12:45 UTC
Labels: feature
