### ISSUE TITLE
Exception Thrown on Search Page 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4855] opened 2022-11-21 15:00 UTC
I'm still investigating how to reproduce this issue.. but so far here it is 

<html>
<body>
<div class="event-property-panel-title" role="presentation" style="box-sizing: inherit; margin-top: 15px; display: flex; flex: 0 0 45px; flex-direction: row; padding-right: 20px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-text" role="presentation" style="box-sizing: inherit; flex: 1 1 0px; margin-left: 10px; overflow: hidden;"><div class="server" role="presentation" title="EXCEPTION" style="box-sizing: inherit; font-size: 16px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">EXCEPTION</div><div class="operation" role="presentation" style="box-sizing: inherit; font-size: 12px; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">ErrorEvent: Script error.</div></div></div><div class="event-property-panel-main" style="box-sizing: inherit; flex: 1 1 auto; overflow: hidden auto; padding-right: 20px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section" role="region" aria-label="Exception Properties" style="box-sizing: inherit; margin-bottom: 15px;"><div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row;"><span role="presentation" style="box-sizing: inherit;">Exception Properties</span><div class="float-right" role="button" aria-controls="aria-485" tabindex="0" focusable="true" style="box-sizing: inherit; margin-left: auto;"><span class="text-button" style="box-sizing: inherit; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; color: rgb(1, 92, 218); cursor: pointer; font-size: 14px;">Show less</span></div></div>

Event time | 11/20/2022, 11:13:29.359 PM (Local time) |  
-- | -- | --
Message | ErrorEvent: Script error. |  
Exception type | ErrorEvent: Script error. |  
Failed method | Unknown |  
Operation Id | cd72f2b29e234bdfbd55c66ed6282bf4 |  
Parent Id | cd72f2b29e234bdfbd55c66ed6282bf4 |  
Severity level | Error |  
Telemetry type | exception |  
Operation name | /en/ |  
Session Id | +K7Np953hB38eNy4gOwOOh |  
User Id | NT3NTKfEMLD7lsY/gWhGOe |  
Device type | Browser |  
Device model | Other |  
Operating system | Mac OS X 10.15 |  
Client IP address | 0.0.0.0 |  
City | Toronto |  
State or province | Ontario |  
Country or region | Canada |  
Browser version | Safari 15.5 |  
SDK version | javascript:2.8.9 |  
Sample rate | 1 |  
Problem Id | ErrorEvent: Script error. |  
Assembly | Unknown |  

</div></div>
</body>
</html>

<html>
<body>
<div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span role="presentation" style="box-sizing: inherit;">Custom Properties</span></div>

errorSrc | window.onerror@https://talent.canada.ca/en/search:0:0 |  
-- | -- | --
url | https://talent.canada.ca/en/search |  
lineNumber | 0 |  
columnNumber | 0 |  
message | ErrorEvent: Script error. |  
typeName | String

</body>
</html>

**Comment by mnigh** [comment] 2022-11-21 15:49
This might be a [CORS](https://blog.sentry.io/2016/05/17/what-is-script-error/) issue, though I am not able to reproduce it on Safari Version 16.1.

**Comment by petertgiles** [comment] 2023-01-13 14:51
Not enough information to diagnose.  Will icebox until we have more clues.

**Comment by vd1992** [comment] 2023-07-04 17:36
Did we get more clues on what is happening here?

**Comment by esizer** [comment] 2023-07-06 16:27
Unable to reproduce in Safari 16.5.1

**Comment by mnigh** [comment] 2023-07-10 15:54
@brindasasi can we close this issue since no one seems to be able to reproduce it? we can always re-open the issue later if someone can reproduce it.

**Comment by petertgiles** [comment] 2023-07-10 16:27
One possible approach - an issue to figure out why we're getting such a generic error report.  Why aren't we getting a detailed message with a stack trace?  Do we need to reconfigure AI?   Add an error boundary?  Adjust our loggers?

**Closed** 2023-07-13 15:29 UTC
Labels: bug
