### ISSUE TITLE
Decide on a default expiry date, placeholder of year past submission

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4627] opened 2022-11-07 20:51 UTC
https://github.com/GCTC-NTGC/gc-digital-talent/blob/917d6335def3d30afc8ce30f93e8098a9c583cae/api/app/GraphQL/Mutations/SubmitApplication.php#L34

**Comment by mnigh** [comment] 2023-03-07 16:20
@GCTC-NTGC/developers is this comment still relevant or is it obsolete and can be removed? if it is still relevant, what do we need to decide on a default expiry date?

**Comment by vd1992** [comment] 2023-04-26 15:19
it would solve #6363 to make it null instead

**Comment by tristan-orourke** [comment] 2023-04-26 17:40
Duplicate of #6363

**Closed by tristan-orourke** 2023-04-26 17:40 UTC
Labels: blocked: question
