### ISSUE TITLE
🐛 Fix typo for P.E.I on search page

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#10018] opened 2024-04-09 12:44 UTC
## 🐛 Bug

Prince Edward Island should be abbreviated as P.E.I not P.E

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/7634aa4b-d6e3-4948-8676-d5c44f727148)

## 🦋 Expected Behaviour

change the copy to P.E.I 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Go to en/search page
2. Check out the Work location list

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

1. Change the copy to P.E.I
2. Search the code base and fix any other occurrences

**Comment by mnigh** [comment] 2024-04-09 13:25
> I don't think this is a typo. PE is the [officially recognized 2 letter code](https://www12.statcan.gc.ca/census-recensement/2021/ref/dict/tab/index-eng.cfm?ID=t1_8#:~:text=%C3%8E.%2DP.%2D%C3%89.-,PE,-11) for Prince Edward Island.

Indeed not a typo, this was intentional: https://github.com/GCTC-NTGC/gc-digital-talent/issues/7214.

**Comment by gobyrne** [comment] 2024-05-09 14:53
Yeah, this is as intended. Closing

**Closed by gobyrne** 2024-05-09 14:53 UTC
Labels: bug, blocked: design, copy
