### ISSUE TITLE
On support form - other form labels are visible through a dropdown menu

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4375] opened 2022-10-18 20:22 UTC
I saw this on the support form.
![image.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/39f13c32-84c9-4686-bfa7-867042c608ec)

**Comment by mnigh** [comment] 2022-10-19 01:53
Duplicate of #4376

**Closed by mnigh** 2022-10-19 01:53 UTC
Labels: bug
