### ISSUE TITLE
Highlight current section in the "Table of contents" UI component

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#9433] opened 2024-01-08 15:04 UTC
## ✨ Summary

[Visit the Figma file]() • Contact @substrae with design questions

This ticket aims to add "highlighting" functionality to the table of contents so that users have a visual and AT signifier for where they are on a given page.

```[tasklist]
### ✅ Requirements
- [ ] Add a bolded "current" state to table of contents items that is triggered when the given section is scrolled to
- [ ] Ensure the a11y equivalent is added (I believe you can use `aria-current` but @esizer please correct me there if necessary)
- [ ] Ensure styles are updated for all 3 states
``` 

## 🔍 Details

<details>
  <summary>📸 Standard tables of content</summary>
  <img src="https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/6960386/18e53c21-ae01-4472-8039-148a62025cc3" />
</details> 

<details>
  <summary>📸 Status tables of content (Incomplete)</summary>
  <img src="https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/6960386/24ec341b-f1e2-487d-a1c7-9798b3d48188" />
</details> 

<details>
  <summary>📸 Status tables of content (Complete)</summary>
  <img src="https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/6960386/e56f017c-e767-4296-871f-363e92fd01d6" />
</details>

**Comment by petertgiles** [comment] 2024-02-22 14:37
Possible duplicate of #8029

**Comment by esizer** [comment] 2024-04-05 17:40
So a few things with this:

- Does seem to be a duplicate of #8029 as Peter mentioned
- I'd be hesistant to use `aria-current` for this. None of the [allowed values](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current#values) seem to make sense for this use case and I don't know of any examples in the wild that do this for scrollspy toc
- I'm wondering what a11y criteria this is attempting to fulfill. We try to keep the accessibility label on tickets that touch some sort of WCAG criteria or need a manual review which are time consuming. So unless there is specific accessibility criteria we need to test, it might be best to remove that label. This seems more like a nice style improvement for visual users not necessarily a11y related so doing a manual review is likely not necessary

**Comment by substrae** [comment] 2024-04-12 12:41
@esizer @petertgiles 

* If it's a duplicate, we can merge them and close this one
* Leaning on Eric here, so yep, remove the a11y label if we don't need to consider any aria labelling

**Closed** 2024-04-25 22:00 UTC
Labels: accessibility
