### ISSUE TITLE
✨ Remove "Recruitments" quick-links functionality

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9030] opened 2024-01-16 16:33 UTC
## ✨ Feature

We should remove these quick-links to subpages inside the "Recruitments" table and let users follow the path to get to where they need to go.

The new design for a recruitment page should be clear enough on how to find these pages.

## 🕵️ Details

Related issue: https://github.com/GCTC-NTGC/gc-digital-talent/issues/8850

✅ Pros: The "Edit" page is both 'state' and 'permission' dependant, which means we would need to do an extra validation on page load/ or on click to figure out whether someone should be able to click on it. Same for 'Candidates'.

❌ Cons: I can forsee powerusers being upset having to do an extra click to get to where they need to be.

## 🎨 Design File and Designer

Include a link to the design file (if it exists) by @Jerryescandon 

### CURRENT TABLE

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/5819514a-3917-4dfa-9a4f-ad2ab451ba69)

### NEW RECRUITMENT PAGE

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/72f7e8d1-d135-4ba7-802c-a0ef9e4353d5)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by mnigh** [comment] 2024-04-22 14:30
@Jerryescandon this issue seems like a duplicate of #8850. can this issue be closed as duplicate?

**Comment by mnigh** [comment] 2024-04-22 14:52
Duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/8850.

**Closed by mnigh** 2024-04-22 14:52 UTC
Labels: feature
