### ISSUE TITLE
🐛 User can bypass verification

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#10889] opened 2024-07-04 16:57 UTC
## 🐛 Bug

Claiming verification after applying lets a user get priority treatment and admins are unable to verify it. It also appears to mess with the sorting. 

## 📋 Steps to Reproduce

1. Claim priority after applying
2. Observe candidate in tables

## 📸 Screenshot

Claim priority after applying here

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/d7c8bb7b-efa9-4e10-8ba0-c43836baf838)

You appear with priority in tables

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/232e3543-e465-4aff-9338-5cf30eff6b5c)

But there is nothing to verify

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/89e0516a-9401-4e33-bc92-e9968aaf53a0)

## 🙋‍♀️ Proposed Solution

- Add new column PriorityStatusClaimed which holds boolean depends on whether the priority claimed during application or not.
- Add new column VeteranStatusClaimed which holds boolean depends on whether the veteran status claimed during application or not.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] If user claimed priority after application , the candidate table should NOT reflect that and same as verification section as well.

**Comment by brindasasi** [comment] 2024-07-08 15:55
The candidate table should reflect the veteran and priority status at the time of application.
Verification should update how this is displayed on the candidate table as well (like it does elsewhere)

**Comment by brindasasi** [comment] 2024-07-08 16:02
We need further discuss whether this table should show live profile or snapshot info.
@GCTC-NTGC/designers  please look at this.

**Comment by Jerryescandon** [comment] 2024-07-08 16:40
Candidate table should represent a user's relationship with a specific process. This means the candidate table should show the "recorded/verified priority status" it should NOT be pulling the status directly from the user's profile.

**Comment by brindasasi** [comment] 2024-07-09 14:19
how about the contact email , phone no,  last name etc?  
@Jerryescandon

**Comment by substrae** [comment] 2024-07-09 14:22
@brindasasi I think account information (e.g. basic personal info, contact info, etc.) should all be live data. @Jerryescandon can expand on what info is application specific, but the likely result will be an annoying mixture.

**Comment by Jerryescandon** [comment] 2024-07-09 14:59
Well, just had a slippery slope of a conversation with Josh, but long story short.
For the all candidate tables use the **profile info** (up-to-date) for the following columns:
- name
- email
- phone
- current location
- preferred communication

**Comment by mnigh** [comment] 2024-07-18 14:44
I cannot reproduce the behaviour described in this issue.

I have tried with a user that is not a veteran and does not have priority entitlement who then applies to a process and then after submitting their application to the process, changes their user profile to be a veteran. The value in the Category column in the applicant table for this applicant is Citizen or Resident.

I have tried with a user that is not a veteran and does not have priority entitlement who then applies to a process and then after submitting their application to the process, changes their profile to have priority entitlement with a priority number. The value in the Category column in the applicant table for this applicant is Citizen or Resident.

@vd1992 is there a scenario that I am missing where the behaviour described in this issue does still occur? if so, can you describe it please? if not, can this issue be closed as can't repro?

**Comment by vd1992** [comment] 2024-07-18 16:29
Ah okay, I think it was resolved with https://github.com/GCTC-NTGC/gc-digital-talent/pull/10924
Was an issue with the frontend rendering and not a verification failure then I think.

Feel free to close, can reopen if it turns out the problem still exists

**Closed** 2024-07-18 17:04 UTC
Labels: bug
