### ISSUE TITLE
Dep: Review Dependencies

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#3638] opened 2022-08-09 15:41 UTC
## Summary

We should take a look at the list of our dependencies and refine them.

## Acceptance Criteria

- [ ] Remove any unused dependencies
- [ ] Dev dependancies are only included under the `devDependencies` and `require-dev` keys
- [ ] Document deps of concern (abandoned, excessively large, barely used, better options)

**Comment by esizer** [comment] 2023-01-26 13:51
This will be easier to review if we hold off until after the merge.... I think 😅

**Comment by brindasasi** [comment] 2023-03-21 14:34
I think the merge part is stale now  😅 .. this is something we could do now?

**Comment by esizer** [comment] 2023-04-27 14:00
One that has been identified is [laravel/sail](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6422#issuecomment-1525630074)

**Comment by vd1992** [comment] 2023-08-15 23:38
Another one is https://www.npmjs.com/package/webpack-config
Has not been updated in a very long time, is the cause of one security alert. 

And we have an oddity where we have something called `"@gc-digital-talent/webpack-config/webpack.base.js"` that is unrelated to that dependency 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/9c36961f-d744-4b03-b12c-39c7c837f74f)

**Comment by esizer** [comment] 2023-08-16 12:44
> And we have an oddity where we have something called `"@gc-digital-talent/webpack-config/webpack.base.js"` that is unrelated to that dependency

We actually are using that it was just named poorly by me (I forgot to namespace it) so it overlaps with an existing package.

**Comment by vd1992** [comment] 2023-08-16 14:59
Oh ya, for sure, definitely using that one. The oddity being two things with such similar names

**Comment by petertgiles** [comment] 2023-10-24 14:28
> What about `cypress-multi-reporters` do we actually need that for anything?

From memory, I think that was an idea Patcon had to report errors directly to the Github results pane.  I think we ended up closing that one as not planned though.

**Comment by mnigh** [comment] 2023-10-24 14:36
> > What about `cypress-multi-reporters` do we actually need that for anything?
> 
> From memory, I think that was an idea Patcon had to report errors directly to the Github results pane. I think we ended up closing that one as not planned though.

Yes, https://github.com/GCTC-NTGC/gc-digital-talent/issues/3977.

**Closed** 2023-10-25 19:05 UTC
Labels: dependencies
