### ISSUE TITLE
♻️ Perf - `ScreeningAndEvaluation_Candidates` is slow

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10932] opened 2024-07-10 16:21 UTC
## ♻️ Debt/Refactor

The Screening And Evaluation Page queries often show up on the slow queries logs.  Let's improve the performance of the `ScreeningAndEvaluation_Candidates` query.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/bbf361d8-8bd1-4f82-8984-cf365d23d0cc)

For now, lets do so by skipping the Policy check per user, and relying on the authorizedToView scope

## ✅ Acceptance Criteria

- [ ] Performance of ScreeningAndEvaluation_Candidates improved
- [ ] Skip policy check for every user
- [ ] Add some phpunit tests to ensure correct roles can see correct users
- [ ] Spin off ticket for improving pagination on kanban page

**Comment by vd1992** [comment] 2024-07-10 16:50
This was the operation we switched to batching since it was performing worse than this. Not sure what else we could do aside from not fetch the `poolId` maybe, that might be unneeded

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/c45922c4-3d06-4338-9b8a-70ba99dbfdad)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/70eb523d-3ca3-463e-9233-259b50414935)

**Comment by esizer** [comment] 2024-07-10 19:20
Likely because we have to resolve individual candidates to check our policy :sob: The query itself isn't that complex :confused:

**Comment by vd1992** [comment] 2024-07-10 20:02
> Likely because we have to resolve individual candidates to check our policy 😭 The query itself isn't that complex 😕

The only bit of cleverness that comes to mind is, when querying candidates for a single pool, you only need to assert team once. The can view pool -> team relation. 
But that'd require a separate query with a different policy function. You'd need to assert the can-view team once, but that the candidate isn't draft for every single one

**Comment by esizer** [comment] 2024-07-11 16:56
So, I seeded 1000 candidates and ran the query for this page dumping out the SQL timings. I noticed that while the individual queries themselves aren't egregious, it may be a combination of how many we fire off in addition to the overhead of eloquent (which I assume is instantiating `PoolCandidate` objects for each).

I think I have come up with some recommendations that should help performance on this query. I have added a tldr; list but provided detail for my reasoning behind them

- Make pool candidates with skill count its own query
- Implement cursor based pagination for better loading strategy
- Avoid using resolved policies and prefer scopes

## Skill Count

Something that I noticed is that every query also fires the `skill_count` portion which is the longest running query at 12-25ms. 

```json
{
  "sql": "select \"pool_candidates\".*, (select null as skill_count from \"skills\" where 0 = 1 and \"skills\".\"deleted_at\" is null) as \"skill_count\" from \"pool_candidates\" where \"pool_id\" in (?) and \"submitted_at\" is not null and \"submitted_at\" <= ? and \"pool_candidates\".\"deleted_at\" is null limit 100 offset 200",
  "milliseconds": 21.49
 } 
```

### Recommendation

Create a separate query for getting pool candidates with skill count and only use it when needed. We never care about skill count here so it is adding execution time/memory unnecessarily. 

## Pagination(?)

Next, there is a `count(*) as aggregate from pool_candidates` which i assume is for the pagination? :thinking: This one isn't that bad (only about 5ms) but it does run for every page we query as well.

```json
{
  "sql":"select count(*) as aggregate from \"pool_candidates\" where \"pool_id\" in (?) and \"submitted_at\" is not null and \"submitted_at\" <= ? and \"pool_candidates\".\"deleted_at\" is null",
  "milliseconds":6.06
} 
```
### Recommendation

Not sure we can do much here. The miniscule time added by the addition query is less than not paginating. I think maybe our best bet here is hope that cursor based pagination opens up more performant options? :thinking: 

I'm thinking we load candidates per step now that we have a field in the database and then implement some chunking of the load by simply loading the first 10 or so and then when the user reaches the bottom of that list we load the next 10.

```php
$query->where('computed_assessment_status->currentStep', $step)->limit(10);
```

## Policy check

Another issue that was already raised was the resolver for the `@can*` directive. I think this is doing the exact same thing as the `authorizedToView` scope :thinking: The difference being, I think it is instantiating an object for every candidate and checking the policy using that :grimacing: 

### With policy
![screenshot_11-Jul-2024_12-40-1720716038](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/c8cecc67-5f09-4f2f-a22e-d9544eec6356)

### Without policy
![screenshot_11-Jul-2024_12-39-1720715998](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/0d149104-1b24-4526-a301-91501457463e)

### Recommendation

I personally don't believe we should be running resolved policies on queries like this. I think the better approach is to use the poorly named `viewAny` policy just to check if the user can view any of the entities then use a scope (`authorizedToView`) to filter out anything they cannot see at the query level.

**Comment by vd1992** [comment] 2024-07-11 18:38
Experimentation, nice 😎 
Overfetching? Sounds like something to be resolved by... more fragments!

### Policy

That seems to have shaved a little bit of time off, but I don't think we'll be removing it. It acts as back-up security and did come into play successfully for the `user.poolCandidates` returning drafts where the scope had a gap

### Skill Count

A bit of a ball of yarn so I don't know

**Comment by esizer** [comment] 2024-07-11 19:15
> Experimentation, nice 😎 Overfetching? Sounds like something to be resolved by... more fragments!

Always the answer :stuck_out_tongue: 

> That seems to have shaved a little bit of time off, but I don't think we'll be removing it. It acts as back-up security and did come into play successfully for the `user.poolCandidates` returning drafts where the scope had a gap

It cut the query times by over half :laughing: . 

The problem is, it needs to instantiate a `PoolCandidate` for every row and then check the policy which is fairly expensive work, also considering the work being done is essentially duplicated :thinking: . The approach we take is not necessarily what you should be doing and we initially misinterpreted the `viewAny` policy so we tend to lean towards a resolved `view` policy instead.

`viewAny` does not mean "view all", it is closer to "view at least one". Policies are more of a "should we allow you to run this code" but we seem to use it more like "should we return this data to the user after the code has run". Which is a large contributor to performance issues on a lot of these queries.

With the `@canResolved` directive, essentially what we are doing is:

1. Querying the data (filtered by `authorizedToView`)
2. Instantiating an object for each row returned <-- This is the expensive part (that needs relationships that need to be retroactivley loaded unnecessarily)
3. Checking the policy (redundant since it should have filtered by a scope already)
4. Returning the data

What should occur is:

1. Check the policy and if it fails return a 403
2. Filter the data the user is allowed to view (our `authorizedToView`)
3. Return data

It is true that have the redundancy has saved us but I think having more robust testing/reviewing is likely better than manufactured redundancy that is over doubling response times to catch preventable errors.


> A bit of a ball of yarn so I don't know

Actually, I think I misread this one :sweat_smile:  . This is the actual query for pool candidates (that happens to include `skill_count`). I think the main offender in that one is the `pool_candidates.*`. Does lighthouse not apply a reduced select based on the fields queried? :thinking: Seems weird we are grabbing all columns in the table when we only really need like 10 :face_with_spiral_eyes:

**Comment by vd1992** [comment] 2024-07-11 20:02
> It cut the query times by over half 😆 .
> 

I'm not good at reading the before and after waterfall views of queries 😛 

> The problem is, it needs to instantiate a `PoolCandidate` for every row and then check the policy which is fairly expensive work, also considering the work being done is essentially duplicated 🤔 . The approach we take is not necessarily what you should be doing and we initially misinterpreted the `viewAny` policy so we tend to lean towards a resolved `view` policy instead.
> 
> ...
> What should occur is:
> 
>     1. Check the policy and if it fails return a 403
> 
>     2. Filter the data the user is allowed to view (our `authorizedToView`)
> 
>     3. Return data
> 

Yeah, you could assert the pool's team check at step one and no longer need to load it for every model you retrieved

> It is true that have the redundancy has saved us but I think having more robust testing/reviewing is likely better than manufactured redundancy that is over doubling response times to catch preventable errors.

I think the degree of redundancy we should have is up to the Dark Lord😆 

> Actually, I think I misread this one 😅 . This is the actual query for pool candidates (that happens to include `skill_count`). I think the main offender in that one is the `pool_candidates.*`. Does lighthouse not apply a reduced select based on the fields queried? 🤔 Seems weird we are grabbing all columns in the table when we only really need like 10 😵‍💫

It's a ball of yarn to me since it follows a thread of objects to use it

`PoolCandidateSearchInput.ApplicantFilterInput.skills` (scope for skills filtering exists here)
`scopeWithSkillCount` exists at the base query though

So I sorta lose track of things easily

**Closed** 2024-07-23 20:34 UTC
Labels: debt
