### ISSUE TITLE
🐛 Table filters do not reset pagination to first page

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5296] opened 2023-01-06 19:22 UTC
## 🐛 Bug

In an admin table when applying a filter (e.g. `Removed` status) if the number of results (e.g. only 3 candidates are returned) doesn't reach that page (e.g. click apply filters on page 3) then the table will be empty. (_Originally posted by @yonikid15 in https://github.com/GCTC-NTGC/gc-digital-talent/pull/5292#pullrequestreview-1239249099_)

## 🦋 Expected Behaviour

The current page is updated to 1 after applying any filters.

## 📋 Steps to Reproduce

1. Visit `/admin/pools/:id/pool-candidates`
2. Click on page 2 in pagination
3. Click on **Filters** button
4. Select **Removed** in status field
5. Click **Show Results**

## 📸 Screenshot

https://user-images.githubusercontent.com/22059495/211079394-a31a97e8-7730-44c1-acd2-c11206573c00.mp4

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Current page is updated to 1 after applying any filters

**Comment by gobyrne** [comment] 2023-01-12 16:15
Tristan says we already fixed this.

**Comment by tristan-orourke** [comment] 2023-01-12 16:16
Closed by #5223

**Comment by tristan-orourke** [comment] 2023-01-18 14:59
Ah, I was premature with this. The problem is resolved for the react-table Table component, but this is still an issue on our apiManagedTables.

**Closed** 2023-01-26 17:39 UTC
Labels: bug
