### ISSUE TITLE
🐛 Partner hiring manager suddenly can't access a process they could once access properly

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#9644] opened 2024-03-05 16:34 UTC
## 🐛 Bug

The hiring manager is able to log in, but when they attempt to view advertisement details, they are unable to and receive a "Sorry, we encountered an error." screen.

## 🦋 Expected Behaviour

The user should be able to view the advertisement details.

## 📋 Steps to Reproduce

Get in touch with Jeanne for more information.

## 📸 Screenshot

![image (6)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/40c1446d-0ee4-4373-8bdf-9276cee45054)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] User can log in as expected
- [ ] User can view their process details as expected

**Comment by esizer** [comment] 2024-03-05 16:59
What role do hiring mangers have @tristan-orourke ? I assume this is related to https://github.com/GCTC-NTGC/gc-digital-talent/pull/9484

**Comment by tristan-orourke** [comment] 2024-03-05 17:04
They probably have Pool Operator role

**Comment by tristan-orourke** [comment] 2024-03-05 17:14
But if that's the case, I can't reproduce this locally, and I also don't see how #9484 would fix it. 

I'll get more details about the user experiencing this.

**Comment by esizer** [comment] 2024-03-05 17:24
> But if that's the case, I can't reproduce this locally, and I also don't see how #9484 would fix it.

Oh yeah, I wasn't expecting it to solve this 😅 I was just wondering if it was related to a gap in assessment plan permissions since that was the only thing that changed. The only time I'd expect to see that error is if they somehow landed on a process page that was not owned by the team they are in 🤔

**Comment by tristan-orourke** [comment] 2024-03-05 20:41
Can confirm that the manager experiencing this issue is a Pool Operator on the same team as the poster they're trying to view. 

But I've rolled back my local env to the same tag as the last deployment, and I still can't reproduce the bug :/

**Comment by tristan-orourke** [comment] 2024-03-05 21:35
This is affecting one user but not other Pool Operators, and clearing the cache didn't help 😭

**Comment by tristan-orourke** [comment] 2024-03-06 20:45
We'll see if this is still happening after our next deployment

**Comment by tristan-orourke** [comment] 2024-03-12 17:41
No longer an issue!

**Closed by tristan-orourke** 2024-03-12 17:41 UTC
Labels: bug
