### ISSUE TITLE
Description not showing up on Skill definition (Tab component)

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3706] opened 2022-08-18 19:18 UTC
## Description

Go to:
My Profile > Edit Experiences > New Experience (Personal)

Steps:

1. Scroll to Step 2: Add skills. 
2. Click on See definition.
3. Box expands underneath but actual description is missing.

![image](https://user-images.githubusercontent.com/16977254/186190671-915b1510-747b-4e6e-9aa7-b0dfff213e1b.png)
![image](https://user-images.githubusercontent.com/16977254/186190837-c0f2aa4a-7e4f-4a46-bc1c-c71a456e1fe2.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment] 2022-08-23 14:47
Can you please add more details @Jerryescandon ?

**Comment by petertgiles** [comment] 2022-09-08 15:54
Duplicate of #3684

**Closed by petertgiles** 2022-09-08 15:54 UTC
Labels: bug
