### ISSUE TITLE
Figure out how to unit test policies effectively

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4636] opened 2022-11-07 21:01 UTC
https://github.com/GCTC-NTGC/gc-digital-talent/blob/9968de2525e4614e54d5a66147279df65539f738/api/tests/Feature/PoolApplicationTest.php#L214

**Comment by vd1992** [comment] 2022-11-07 21:31
duplicate of #3643

**Closed by vd1992** 2022-11-07 21:31 UTC
