### ISSUE TITLE
🐛 Reported issue -  HTTP 403 on save experience

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7522] opened 2023-08-03 20:31 UTC
> __Note__
This is spun off from #7172

## 🐛 Bug

The save and go back button is giving several users errors or not going back. 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Safari 16.5.2 on macOS 13.4.1 (c).
- **Browser**: both Safari and Firefox 115.0.2 (on the same version of macOS, 13.4.1 (c)) 

### Notes from support ticket
Source: https://talent-cloud.slack.com/archives/CB424V61J/p1691003440721689?thread_ts=1688583583.502789&cid=CB424V61J

I am using Safari 16.5.2 on macOS 13.4.1 (c).
In the connection inspector I see the following:
```
URL: https://talent.canada.ca/graphql
Status: 403 Forbidden
Source: Network
Address: 13.71.189.247:443
Initiator: InstrumentHooks.js:67
```
The value of "ts-createExperience-work" is:
```json
{"details":"","role":"Software Developer","organization":"Start Communications","team":"","startDate":"2016-03-01","currentRole":false,"endDate":"2018-04-01","skills":[]}
```
I have existing work experience that takes place after this work experience, if that's relevant! I am going to try deleting my existing work experiences now and re-enter them in chronological order.

I've removed the previous work experience off of my profile and tried to resubmit my work experience in both Safari and Firefox 115.0.2 (on the same version of macOS, 13.4.1 (c)) and got the same error for both. I double checked that I didn't have anything saved in my browser cache. I also ensured that tracking protection was disabled for "https://talent.canada.ca/".

 I believe I have found the issue: If I put "Start" in the organization field, the form blocks the input with a 403 forbidden. If I shorten it to "Star", there's no issue.
I could submit with a non-breaking zero width space between the "r" and the "t" characters, but I'd imagine that might also cause problems

## ✅ Acceptance Criteria

- [ ] Bug replicated
- [ ] Can submit work experience without triggering incorrect HTTP 403

**Comment by petertgiles** [comment] 2023-08-03 20:36
Since it's a 403 and not a 500, I wonder if something is going wrong in the policy?

**Comment by vd1992** [comment] 2023-08-03 22:38
That doesn't look right either

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/10418363-ed9e-4e3b-884b-5270e3ea6d51)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/fc8ff174-0575-4684-8200-6bc0b1ae8e96)

**Comment by vd1992** [comment] 2023-08-03 22:54
I tried the input in a mutation and it worked, so don't think the input itself has problems. Yeah, authorization and policy maybe

**Comment by esizer** [comment] 2023-08-04 12:59
Was unable to reproduce with the following payload:

```json
{
    "query": "mutation CreateWorkExperience($id: ID!, $workExperience: WorkExperienceInput!) {\n  createWorkExperience(userId: $id, workExperience: $workExperience) {\n    id\n    __typename\n  }\n}",
    "operationName": "CreateWorkExperience",
    "variables": {
        "id": "58148c9f-90d3-43c5-a46b-6964dcfe037b",
        "workExperience": {
            "details": "",
            "skills": {
                "sync": []
            },
            "role": "Software Developer",
            "organization": "Start Communications",
            "division": "",
            "startDate": "2016-03-01",
            "endDate": "2018-04-01"
        }
    }
}
```

That policy (while I see nothing wrong with it) is different from the others. 🤷‍♀️ 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/88db0e222ce0f98c75e00c13d100f5674b7e2194/api/app/Policies/ExperiencePolicy.php#L20-L24

I think it would be safe to do:

```php
public function creat(User $user, $model)
{
    return $user->can('update', $model->user);
}
```

**Comment by brindasasi** [comment] 2023-10-19 14:05
@petertgiles @vd1992 is this something we just fixed with firewall thing?

**Comment by vd1992** [comment] 2023-10-19 15:03
> @petertgiles @vd1992 is this something we just fixed with firewall thing?

95% sure, so lets close this and reopen if needed be, but probably won't need to as there are multiple issues like this already making this redundant

**Closed as not planned by vd1992** 2023-10-19 15:03 UTC
