### ISSUE TITLE
ApiEnums - pull these directly from the graphql schema

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4631] opened 2022-11-07 20:55 UTC
https://github.com/GCTC-NTGC/gc-digital-talent/blob/9968de2525e4614e54d5a66147279df65539f738/api/database/helpers/ApiEnums.php#L5

**Comment by petertgiles** [comment] 2023-01-25 17:41
Duplicate of  #2400

**Closed by petertgiles** 2023-01-25 17:41 UTC
