### ISSUE TITLE
✨ Update `/logged-out` messaging based on how it occurred

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#7811] opened 2023-09-01 15:57 UTC
## ✨ Feature

We would like to present users with different messaging based on how they were logged out of the application.

## 🕵️ Details

Currently, we send users to a page that lets them know they were logged out. However, the messaging implies it was done intentionally by the user and that is not always the case. We have a few scenarios where users could be logged out for other reasons including:

- They have an invalid token
- Their account was deleted

We would liked the slightly tweak the copy to give users more contextual information on that page that tells them why they were logged out if it was not their choice.

## 🎨 Design File

> **Note**
> Maybe this should go through design first to determine the type of alert we display and hammer out the appropriate copy?
> Anyway, I'll leave this section in incase we end up with a design file for this.

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

The automatic logout (unintentional) happens in the `ClientProvider`. Adding a query param to the `logout()` then reading it and changing copy should be all this needs.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Users are redirected to specific `/logged-out` page based on the reason

**Comment by marc-donofrio** [comment] 2023-09-25 16:11
Here are my suggests for the copy:
Token: "Your login session has expired, please login again." 
(let me know if this makes sense for an invalid token or if there are other reasons a token become invalid.)
Deletion: "Your account has been deleted. To access the platform again, please register for a new account."

**Comment by gobyrne** [comment] 2024-01-04 15:35
Ok, let's be darn sure we're not telling anyone that there account was deleted unless it really was. Maybe soften the language just in case.

@substrae can you add this to your list (or leave a comment for discussion)

**Comment by gobyrne** [comment] 2024-01-04 21:06
Closing as a duplicate of #8652 

@substrae nvm :)

**Closed by gobyrne** 2024-01-04 21:06 UTC
Labels: feature, blocked: design
