### ISSUE TITLE
My Skills - Skill Search input component

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#1544] opened 2021-12-23 19:47 UTC
# Description
This component shows a single text input. It takes in a list of skills and a `updateFilteredSkills` handler function as props. Whenever the value of the text input changes, it runs a filter function to determine which skills match the value and calls `updateFilteredSkills` with that list.

The filter function should include any skills whose name, or any of its keywords, include the text in the search box. It should be case insensitive, and should only use the skill name and keywords matching the current locale. It should gracefully ignore accents (eg  e should match è).

A few shortcuts can be used to improve performance. If the search input value is empty, simply return all skills. Perhaps require 2 or 3 characters minimum before searching filtering at all. A debounce function may be used (see the Talent Search form) to wait some minimal time after typing finishes to start a search.

The search function is an excellent candidate for some unit tests.

# Definition of Done
- [ ] This component should appear in storybook. It should be shown along with a list of skills which meet the search term, to show it working
- [ ] Some unit tests proving the search function works correctly and the component returns the expected skills.

**Comment by tristan-orourke** [comment] 2022-01-12 15:54
Duplicate of #1479

**Closed by tristan-orourke** 2022-01-12 15:54 UTC
Labels: feature
