### ISSUE TITLE
🐛 No bearer token sent in first graphql request after login

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7885] opened 2023-09-12 18:45 UTC
## 🐛 Bug

We're experiencing an issue where the first graphql request after logging in (getCurrentAuthorizedUser) is not sent with the bearer token.  The second (e.g. ApplicantInformation) and subsequent requests do have it.  What this looks like to the user is that they can log in but get a "Sorry, you are not authorized to view this page." error.  If they refresh the page they can proceed without further problems.

## 🕵️ Details

- Commit 93607e85e works but 02c92589c does not so I'm pretty confident that the issue started with https://github.com/GCTC-NTGC/gc-digital-talent/pull/6547.
- The issue only occurs with prod builds.  Dev builds do not exhibit the problem.
- Happens with both mock auth and SiC.

## 📋 Steps to Reproduce

1. Set up the project with urql V4 and auth-exchange V2.
2. Build in prod mode.
3. Log in.
4. Observe the "Sorry, you are not authorized to view this page." error.

## 📸 Screenshot

First request:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/ba81673d-060d-4733-a303-7ec39bf80959)
Second request:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/fc9a405c-749c-482e-abc9-cbd9111fb554)

## ✅ Acceptance Criteria

- [ ] With a prod build, every graphql request after log in has the "authorization" header.

**Comment by tristan-orourke** [comment] 2023-09-12 21:41
We should get a fix for this in before we deploy this week. I thought I could make the quick fix of reverting #6547, but I can't reproduce the bug in the first place! Someone else should take a look.

**Comment by vd1992** [comment] 2023-09-12 23:06
Replicated locally, not 100% sure what is required to make it happen but I got it by trying combined the following

- npm run build:fresh
- restart mockauth container
- API refresh
- commented out default login in API env file
- have browser cache enabled

Then got the below logging, `getCurrentAuthorizedUser` returned null. Refreshing page resolves things. 
After that, logging out and then back in replicated the issue continually without needing to redo things like building. 

React-Router console error below may be the most useful bit of info? 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/694b4ae0-9b5a-401f-b36a-956374d1d04d)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/d44a95ad-a57d-4fda-a6a2-d8798d4cc378)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/77658d65-672d-4f83-bb46-b111501e67e3)

**Comment by vd1992** [comment] 2023-09-13 00:11
Experimenting...
It appears upon logging in, the access token it fetches is not set yet and so is null. Subsequent page loads it fetches an access token that is set so no problems arise. 

Added this logging

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/0db6d99f-ddee-4344-a432-911d9a2a527b)

Upon logging in I get

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/62b8fd6c-fffd-4e1a-b2a6-ee5c18ac91f2)

Upon refreshing I get

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/65e13cb1-ea42-486f-ba29-41569f64ac33)

**Closed** 2023-09-13 16:53 UTC
Labels: bug, interruption

**Comment by brindasasi** [comment] 2023-09-13 19:17
am cutting off next patch with this commit
