### ISSUE TITLE
Publish pool dialog - expiry date off by 1

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4273] opened 2022-10-12 17:55 UTC
Observe how I set the publish date to Oct 31 but the publish dialog shows Oct 30.

https://images.zenhubusercontent.com/364642496/12cd5065-0c76-4be3-b42d-d95544f4986e/simplescreenrecorder_2022_10_12_13_52_48.mp4

Probably covered by  #3315

## Acceptance Criteria
- [ ] When choosing an expiry date, user selects a date (not a time), but the UI informs the user that the job will close at 11:59 PM Pacific Time on their chosen date.
- [ ] A datetime, set to 11:59 PM Pacific Time on the chosen date, is submitted to the API. (The api should be expected to convert to UTC before saving it.)
- [ ] When displaying the expiry date anywhere on the Edit Pool page, and when initializing the date input with existing data, first convert the datetime from the api from UTC to Pacific Time, and show very explicitly that it is a time in a particular timezone.

**Comment by vd1992** [comment] 2022-10-12 18:09
the cause seems simple enough
updating it submits something at day of, midnight, so 00:00 UTC time, then when it loads it from the database, the time zone conversion bumps it to the day prior

![image](https://user-images.githubusercontent.com/40485260/195415434-0ca45cfe-431a-4a71-b34b-c93609438d0a.png)

the tricky part is a solution 
proposal: 
given pool expiry times are known (11:59 PM Pacific time), an intermediary function can be added so what gets sent to database is actually 06:59 AM UTC (7 hour difference)

**Comment by vd1992** [comment] 2022-10-12 18:10
I think the big sticking point might be, pools will not close on the same day for everyone
if closing time is 11:59 PM PST, it closes 02:59 AM for EST, therefore the expiry date is actually two possible dates

**Comment by petertgiles** [comment] 2022-10-14 20:17
@Jerryescandon For the AC of this issue we need to inform the user of the time zone nuance.  For the picker I had two ideas:

Option 1: A tooltip with the question button like Process Number
![image](https://user-images.githubusercontent.com/8978655/195932945-3c90de39-f55f-4941-8874-20ba09fed294.png)

Option 2: Sub text like Your impact
![image](https://user-images.githubusercontent.com/8978655/195933347-6062d3c2-a8d8-4d4d-9446-ecd6cac9d892.png)

Same design needs for Extend Date:
![image](https://user-images.githubusercontent.com/8978655/195934585-598b67b3-0b43-42f1-a471-43e834fa160d.png)


Same design needs for the publish dialog though it might not be 11:59 PM if it was manually closed:
![image](https://user-images.githubusercontent.com/8978655/195933888-4e6e2716-136f-4dae-8c0c-ca69ee4516eb.png)

What about Admin View Advertisement?  Do we show this in Pacific or local?
![image](https://user-images.githubusercontent.com/8978655/195934387-a535dd2c-d1be-46c1-a9d5-2f2a45ce7fdb.png)

And Local View Advertisement?  Pacific or local?
![image](https://user-images.githubusercontent.com/8978655/195934876-814a68be-c067-46ef-b9a8-d9610b951dc8.png)

**Comment by petertgiles** [comment] 2022-10-14 20:22
To help illustrate the problem: see how 11:59 PM Pacific is on a different day in Ottawa:

[![image](https://user-images.githubusercontent.com/8978655/195936294-63d068ce-cb12-40de-8b80-633c39b5182b.png)](https://www.worldtimebuddy.com/?qm=1&lid=6094817,6173331&h=6094817&date=2022-10-14&sln=2.5-3&hf=1)

**Comment by esizer** [comment] 2022-10-14 22:10
See: https://github.com/GCTC-NTGC/gc-digital-talent/issues/4041#issuecomment-1279468760

tldr; We are storing the wrong time in the database which is causing a lot of problems on the frontend.

**Comment by petertgiles** [comment] 2022-10-18 14:18
Add to scope: fix https://github.com/GCTC-NTGC/gc-digital-talent/pull/4366/commits/78fa60dd556c3cfe830dfc54c183ccef05095bd9

**Closed** 2022-10-26 14:43 UTC
Labels: bug, interruption
