### ISSUE TITLE
🐛 Inconsistency in table filter modal

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8776] opened 2023-12-12 22:35 UTC
## 🐛 Bug

Unexpected behaviour when closing the table filter modal without clicking "show results".

## 🦋 Expected Behaviour

There are three ways to close the modal: clicking the "Show results" button, clicking the "Clear filters", and exiting the modal in some other way like clicking outside the modal or with the escape key.

### Show results
If I open the filter, change some filters, and click "Show results", then it works as expected. Three things happen:
  1. The modal closes
  2. The table updates to show the result of searching
  3. The filter button updates to show the number of active filters

### Clear filters
If I open the modal, change some filters, and click "Clear filters", then:
  1. The modal closes
  2. No new search is run, the table is unchanged
  3. The modal forgets about any filter changes I made. The number of active filters remains unchanged, and if I reopen the model, the previous filter changes I made have disappeared.

Our previous behaviour for "clear filters" was to clear all active filters and then rerun the search. This new behaviour would make sense to me, **if** we change the text from "clear filters" to "cancel".

### Other
If I open the modal, change some filters, and close the modal with the escape key, then:
  1. The modal closes
  2. No new search is run, the table is unchanged
  3. The filter button updates to show the number of active filters I left in the modal. **This no longer corresponds to the active filters reflected in the table results.**

It doesn't make sense to me that the number of active filters shown on the button or in the modal no longer reflects the "active filters" determining the results.

## 📋 Steps to Reproduce

See above

## 📸 Screenshot

Table with filter button with number of active filters:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/363fedd4-ab42-4f48-a21a-dc729f8bdd20)

"Clear filters" and "Show results" buttons on filter modal:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/1c9f01e2-670a-421b-8976-e8e29aa666b8)

## 🙋‍♀️ Proposed Solution

a) Change "Clear filters" text to "Cancel", and ensure that exiting the modal without clicking "Show results" always triggers the same behaviour as clicking "Cancel"

b) Change "Clear filters" behaviour to remove any active filters, reflect that in the UI (the modal inputs and the number on the button) then re-run the search. Closing the modal in other ways should trigger the "cancel" behaviour currently triggered by the "clear filters" button.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Clear filters button restores default, and reruns search
- [ ] Closing the filter in other ways discards any staged filters
- [ ] count only updates when filters are submitted, when closed it should reset to previous number

**Comment by esizer** [comment] 2023-12-13 14:48
> 3\. The modal forgets about any filter changes I made. The number of active filters remains unchanged, and if I reopen the model, the previous filter changes I made have disappeared.

Is this happening on a specific table? I just tested the general pool candidates page and it seems to work as intended 🤔 Unless the functionality in the video is what you are describing as not intended since it only resets to the default filters, not a complete empty state (which in itself is a little odd).

https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/23a20586-d666-4283-88e4-f1b57cf2e02e

> It doesn't make sense to me that the number of active filters shown on the button or in the modal no longer reflects the "active filters" determining the results.

Oops, yeah that is not great 😬 . The number reflects the current form state (really the only state we are aware of), counting any non-null fields. We may need to store the previous submitted values since the client is not aware of what filters were applied to the previous request, just the ones you have "staged" to be submitted.

**Comment by substrae** [comment] 2023-12-13 14:51
I haven't had time to test this, but I agree with @tristan-orourke's `b)` proposal. The behaviours should be as follows:
* Show results submits the currently selected filters, closes the dialog, and runs the search 
* Clear filters should remove ALL selected filters, close the dialog, and run the search sans-filters
* Cancel / X / clicking the background should ignore ANY changes made in the dialog, close it, and keep the table as is, including the original filters that were selected when the dialog was open

**Comment by tristan-orourke** [comment] 2023-12-13 15:01
>> 3. The modal forgets about any filter changes I made. The number of active filters remains unchanged, and if I reopen the model, the previous filter changes I made have disappeared.
>
> Is this happening on a specific table? I just tested the general pool candidates page and it seems to work as intended 🤔 Unless the functionality in the video is what you are describing as not intended since it only resets to the default filters, not a complete empty state (which in itself is a little odd).

Oops, you're right @esizer, I'm not sure how I confused that! The "Clear filters" button **is** re-running the search. I guess the question is: should "Clear filters" remove **all** filters, or reset the filters to the page defaults? The latter might be nice, but might also merit a copy change. @substrae thoughts?

**Comment by tristan-orourke** [comment] 2023-12-13 15:07
> The number reflects the current form state (really the only state we are aware of), counting any non-null fields. We may need to store the previous submitted values since the client is not aware of what filters were applied to the previous request, just the ones you have "staged" to be submitted.

I think the problem is that it's confusing to have "staged" changes which aren't reflected in the search. We should either submit a new search or discard the staged filters. 

Instead of storing the previous _submitted_ filters, would it be easier to save a snapshot of the filters at the moment when you open the modal?

**Comment by esizer** [comment] 2023-12-13 15:09
> Oops, you're right @esizer, I'm not sure how I confused that! The "Clear filters" button **_is_** re-running the search. I guess the question is: should "Clear filters" remove **all** filters, or reset the filters to the page defaults? The latter might be nice, but might also merit a copy change. @substrae thoughts?

I agree with that @substrae mentioned and all functionality outlined in the comment:

> I haven't had time to test this, but I agree with @tristan-orourke's `b)` proposal. The behaviours should be as follows:
> 
> * Show results submits the currently selected filters, closes the dialog, and runs the search
> * Clear filters should remove ALL selected filters, close the dialog, and run the search sans-filters
> * Cancel / X / clicking the background should ignore ANY changes made in the dialog, close it, and keep the table as is, including the original filters that were selected when the dialog was open

This is how I would expect it to work as a user.

> Instead of storing the previous _submitted_ filters, would it be easier to save a snapshot of the filters at the moment when you open the modal?

Oh yeah, that would be good approach as well! 👍

**Comment by tristan-orourke** [comment] 2023-12-13 17:47
There were some concerns at standup about why we have a "Clear filter" action in cases when we have some filters initialized by default. @substrae what do you think about replacing the "Clear filters" button with a "Reset filters" button, which resets them to the default/recommended for the page?

(This also turns out to be much easier, technically 😄 )

**Comment by substrae** [comment] 2023-12-13 18:46
@tristan-orourke I'm fine with that for sure - I wasn't aware we had been setting "default" filters - something I don't really agree with, but if they exist, the "clear" or "reset" should bring those defaults back when used.

**Closed** 2023-12-19 18:14 UTC
Labels: bug
