### ISSUE TITLE
Honesty pledge (boring in DEI section)

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4705] opened 2022-11-10 18:57 UTC
Part of MLP Epic #4704
 
## Description
Honesty pledge (boring in DEI section)

## Acceptance Criteria
- [ ] ...

**Comment by petertgiles** [comment] 2023-01-25 18:01
Duplicate of #5316 ?

**Comment by Jerryescandon** [comment] 2023-01-25 18:32
Yeah, basically that work is global and should affect the entire platform not just IAP, all Indigenous self id options should be available to all users.

**Comment by petertgiles** [comment] 2023-01-25 19:17
Closing as duplicate.  Reopen if something is unique to this issue.

**Closed by petertgiles** 2023-01-25 19:17 UTC
Labels: duplicate, feature, blocked: design
