### ISSUE TITLE
Add workflow to validate lighthouse-schema.sql is up-to-date

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#1775] opened 2022-01-17 20:37 UTC
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/1770#issuecomment-1014867258

This came up earlier in #1691, and already bit us, in that chromatic is failing due to an easy-to-miss new task of updating an artifact:

> [I can imagine a concern that this committed file would get out of sync with the generated one. To mitigate, we could later add another validation workflow, to confirm in each PR that the committed graphql file is in-sync with a generated one.](https://github.com/GCTC-NTGC/gc-digital-talent/issues/1691)

I can add a workflow to ensure this gets flagged before a PR is merged. It will.

- checkout the PR branch
- build the minimal amount of api subproject to run artisan commands
- re-generate the lighthouse-schema.graphql file
- look for a dirty git workspace
- fail if there are any changes in this file

Sound like an OK approach?

**Comment by patcon** [comment] 2022-01-17 21:00
Actually, seems that I misdiagnosed. Leaving this, but opening a new ticket for fix :)

**Comment by tristan-orourke** [comment] 2022-01-17 22:23
Sounds like a good approach, and definitely something we want.

**Comment by petertgiles** [comment] 2022-01-21 16:15
@patcon, shall we leave this one for you?

**Comment by gggrant** [comment] 2022-03-17 18:37
Duplicate of #1855

**Closed by gggrant** 2022-03-17 18:37 UTC
