### ISSUE TITLE
🐛 Default publishing group filters on candidates table - EX candidates hidden by default

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8658] opened 2023-12-01 20:23 UTC
## 🐛 Bug

We recently launched an EX process. The process information page said 26 applications received. But when we looked at the candidate table, nobody was there. We determined that the EX group was being filtered out.

## 🦋 Expected Behaviour

The publishing group that the process (pool) is associated with should be filtered in by default for any process.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/81b84d97-1d44-4a4b-a2bd-1c86a47e18da)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Publishing group that a process is associated with is always selected in the filters by default

**Comment by brindasasi** [comment] 2023-12-06 15:42
Looks like there is no default filter for Publishing Group any more in latest main. Confirmed in UAT as well as of release 2.12.8 . 
Closing this issue as fixed.

**Closed as completed** 2023-12-08 18:40 UTC
