### ISSUE TITLE
✨ Disorienting when paging to the last page of table

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7836] opened 2023-09-06 17:57 UTC
## ✨ Feature

When paging through a table, moving to the last page suddenly makes the table component smaller - especially if there are only one or two rows on the last page.  This causes a big layout shift that can be disorienting.

## 🕵️ Details

[From Eric](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7831#discussion_r1317608479):
> I think the trouble with this is that we need to know some crucial information to do this that would be difficult to determine.
    How many rows? - Easy because of page size
    Average row height - Hard because rows are not uniform

My thoughts:
- I wonder if maybe just making a solid guess would be enough to minimize the layout shift?  
- Maybe animating the change would help the user to track the component through its size change?

## 📸 Screenshot

[Add a screenshot of the new feature (if possible).](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/c5f00aba-7b6d-436c-9621-8fe40d3c9fef)

## ✅ Acceptance Criteria

- [ ] Paging between a full page and a nearly empty page isn't disorienting

**Comment by gobyrne** [comment] 2023-10-24 17:27
@substrae is this as intended?

**Comment by substrae** [comment] 2023-10-24 18:08
@gobyrne @petertgiles @esizer 

Hmm. If layout shift is a concern in this context, then we should also be concerned with layout shift created by changing to any table page that happens to have wrapped content in rows, as this also has the potential to be a dramatic shift. To be honest however, I'm not sure there's a great solution to this problem. We could set a minimum height on the table based on the single line row heights (we know exactly how tall a single line is, because we've set the padding and the line-height of text... We know how many rows the table is showing at any given time too. We could try an animate the table's height as Peter has suggested, but I have a weird feeling it might not be as smooth as we hope.

**Comment by gobyrne** [comment] 2024-01-04 18:17
This isn't perfect, but it's not that bad either. Closing with #wontfix

**Closed** 2024-01-08 13:41 UTC
Labels: feature, blocked: design, accessibility
