### ISSUE TITLE
🐜 JAWS Focus change issue at the bottom of the About Me form

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5478] opened 2023-01-25 22:17 UTC
## ❌ Current behaviour (issue)
When a user attempts to navigate away from the citizenship component to account details,  JAWS focus jumps from the Account Details component back to the citizenship component and then the citizenship requirement message w
### AT configuration: 
JAWS, Windows, Edge
### Fable video clip: 
[Focus change issue ](https://app.makeitfable.com/share/63caeff5035e44001a77d81d)
### How to reproduce
1. Open JAWS
2. Navigate using your keyboard to profile and then About Me Section 
3. Tab down  past the Citizenship component. 
4. Read the About Details header. 
## ✔ Expected behaviour (fix)
Focus remains in the account details section and does not skip back to the citizenship component. Citizenship requirement information is not read as the user attempts to navigate through the beginning of the Account Details Section.
### Potential WCAG Criteria for consideration: 
[2.4.3 Focus Order](https://www.w3.org/WAI/WCAG22/Understanding/focus-order)
### Acceptance Criteria
A set of assumptions which, when tested, verify that the accessibility requirement was met.
- [ ] Focus remains in the account details section when using keyboard navigation. 
- [ ] Citizenship requirement information is not read as the user navigates into the Account Details form component.

**Comment by petertgiles** [comment] 2023-03-28 19:53
Could you please help me understand what happened in this video?  It appears the context helper was already open and the user was focused below it.  Why was the context message then the form radio options read out again, pulling focus up?  What triggered this?  When I try navigating through the form by keyboard I can't replicate the focus jump.

**Comment by RM-1978** [comment] 2023-04-17 16:00
@petertgiles So sorry for the delay. The user was using forms mode in JAWS and was simply tabbing through the page.

**Comment by esizer** [comment] 2023-04-20 14:42
> @esizer Another one for JAWS testing 😬 Are you able to replicate this and understand what's going on?

Was not able to reproduce this exactly. What happens for me is, when I request the citizenship section to be read, for some reason the page jumps to the top but all the text is read in the correct order. My best guess would be the hidden text we have as part of `fieldset` to produce proper markup for keep the expected layout with that context toggle button. 🤷‍♀️

**Comment by petertgiles** [comment] 2023-04-20 14:44
OK, so I'll scope the issue to "JAWS - When reading citizenship info the focus jumps to the top"?

**Comment by RM-1978** [comment] 2023-04-20 14:46
So, I think the scope of the issue might be that the focus is jumping with JAWS (top or bottom-depending on user)?

**Comment by petertgiles** [comment] 2023-04-20 14:59
OK, it sounds like maybe we have enough to take a first stab at it - but not conclusively fix it.  Thanks so much!

**Comment by esizer** [comment] 2023-05-17 17:38
So, I did another test with this to do two things:

1. See if I could once again reproduce what we saw during the Fable test
2. Try to understand the issue a little more

What I have found is:

1. I still can't seem to reproduce the Fable test exactly
2. It definitely jumps to the top of the page every time we encounter hidden text
    - In the video I was able to capture, you will notice every time we land on hidden text (context button, fieldset legends) the scroll position jumps to the top.
    
I feel as though this issue highlights to problems with the hidden text and why we should avoid it if possible. Not all users who use JAWs (or another AT) are completely sightless and having the scroll position jump around can be very disorienting to some users.

I think the only fix for this is to attempt to reduce our reliance on hidden text and attempt to locate them and rewrite them to no longer require it which could be quite challenging 😅 


https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/95e70e28-8eb3-4461-a981-6cebcc1a8662

**Comment by esizer** [comment] 2023-06-15 14:11
So, looks like the idea about it being hidden text may have been accurate. Now that we no longer use any hidden text in inputs, the issue appears to be resolved 😄 No more weird scroll jumping and the cursor moves logically announcing items appropriately.


https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/78054b52-b977-40d4-a1fd-4d5bc0f2df9f

**Closed** 2023-06-20 18:23 UTC
Labels: accessibility
