### ISSUE TITLE
PHP 7.4 Active Support has ended

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#1250] opened 2021-11-29 19:21 UTC
Active support for PHP 7.4 ended yesterday (November 28, 2021) and end of life will occur a year from yesterday (November 28, 2022). Some dependencies, including doctrine/dbal, now require at least PHP 8.0 (see https://github.com/GCTC-NTGC/gc-digital-talent/issues/1249).

Considerations to migrate should include looking through this guide: [Migrating from PHP 7.4 to PHP 8.0](https://www.php.net/manual/en/migration80.php)

**Comment by petertgiles** [comment] 2021-11-29 20:25
Would be good to update the maintenance container at the same time.  It's [currently pinned to 7.4](https://github.com/GCTC-NTGC/gc-digital-talent/blob/5843c3744a964dbcecdaa8db31c7f3009774a865/infrastructure/maintenance-container/Dockerfile#L8) to mimic the PHP container.

Also, we may want to consider [specifying the platform PHP version](https://andy-carter.com/blog/composer-php-platform) in the composer.json files.  It might help us avoid pulling in incompatible dependencies accidentally.

**Comment by petertgiles** [comment] 2021-12-02 19:04
Our composer files list the apps as having a top-level dependency of php version ^7.3|^8.0.  This should probably be updated as well.

**Comment by mnigh** [comment] 2021-12-08 20:27
Another good reason to proactively upgrade to PHP 8.0 is that the Laravel 9, which will be released in January 2022, [will require a minimum of PHP 8.0](https://laravel.com/docs/8.x/releases#support-policy).

**Comment by tristan-orourke** [comment] 2022-11-17 15:04
Closed as a duplicate of #3560

**Closed by tristan-orourke** 2022-11-17 15:04 UTC
Labels: debt, infrastructure
