### ISSUE TITLE
🐛 Bug Report - Admin - Issue when selecting multiple checkboxes in Users table

### ISSUE THREAD

**Issue by MaddyDaigle** [GCTC-NTGC/gc-digital-talent#5255] opened 2023-01-03 18:18 UTC
## 🐛 Bug

An error occurs if the user tries to select more than 3 checkboxes on the left-most column of the table.  A message appears at the bottom left of the table where the download links should be that says "Oh no...[GraphQL] Internal server error"

## 🦋 Expected Behaviour

The user should be able to select as many checkboxes as they want.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Mac OS Montery
- **Browser**: Chrome

## 📋 Steps to Reproduce

1. Go to the Users page in the Admin application (https://uat-talentcloud.tbs-sct.gc.ca/en/admin/users)
2. Click on more than 3 checkboxes

## 📸 Screenshot

<img width="1220" alt="Screen Shot 2023-01-03 at 1 12 59 PM" src="https://user-images.githubusercontent.com/1794660/210417500-0a31521e-e79f-4589-88a6-561947eeeb66.png">

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] User can select more than 3 checkboxes in the table

**Comment by gobyrne** [comment] 2023-01-05 20:40
I'm not able to reproduce on UAT today.

**Comment by patcon** [comment] 2023-01-12 18:15
Closed as can't repro

**Closed** 2023-01-12 18:14 UTC
Labels: bug
