### ISSUE TITLE
Pin versions of docker image for GH workflows

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5104] opened 2022-12-13 13:59 UTC
We should probably be using pinned versions of the docker images in the GitHub workflows.  Otherwise our images will change without us being ready for it.  For example:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/cdd91557-f730-4caa-a12f-0b4388c24c9b)

**Comment by mnigh** [comment] 2022-12-13 14:50
@petertgiles Possible duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/4102?

> Update all uses of "ubuntu-latest" to specific versions

**Comment by petertgiles** [comment] 2022-12-13 14:53
> @petertgiles Possible duplicate of #4102?
> 
> > Update all uses of "ubuntu-latest" to specific versions

LOL, and it was even one my mine.  :face_with_spiral_eyes: Good catch!

**Closed** 2022-12-13 14:56 UTC
Labels: tooling
