### ISSUE TITLE
🐛 Use of pool/process/recruitments interchangeably

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#9591] opened 2024-02-29 18:13 UTC
## 🐛 Bug

Pool/process/recruitment is used interchangeably and gets sort of confusing, especially when breadcrumbs are involved. 
When is it correct to use one over the other?

## 📸 Screenshot

You click on processes

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/df995568-84b0-46db-b0ad-6bcf36035508)

Are taken to a page called processes with that in the breadcrumbs too but the URL contains pool and you have the option to add a pool

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/2b569994-2f9c-4b66-ad6a-139b003471ec)

You click on a process/pool and go to edit it, the breadcrumbs shift to using the word recruitment 
Clicking on recruitments takes you back to processes

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/5c0634bb-9e2e-417a-a100-58a857bbee38)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by tristan-orourke** [comment] 2024-03-06 15:32
Duplicate of #9643

**Closed by tristan-orourke** 2024-03-06 15:32 UTC
Labels: copy, blocked: copy
