### ISSUE TITLE
🐛 Storybook - TreeView story unstable

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6758] opened 2023-05-31 12:56 UTC
## 🐛 Bug

The TreeView story is unstable and is triggering Chromatic diffs

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/0c9575bd-d97a-4740-b78a-27635935839c)Add a screenshot (if possible).

## ✅ Acceptance Criteria

- [ ] The TreeView story is stable and does not trigger diffs

**Comment by mnigh** [comment] 2023-05-31 16:00
Duplicate of #6768. This issue was created first, but the other issue has a proposed solution! 😈

**Closed by mnigh** 2023-05-31 16:00 UTC
Labels: bug
