### ISSUE TITLE
Refactor talent search page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2800] opened 2022-05-18 12:51 UTC
The talent search page could probably use some love.  It sends an unnecessary first query without a pool ID filter and the way it is storing state could probably be improved.  @esizer has some ideas on how to level it up.
```
I believe we could simplify that form significantly, unless I'm just misunderstanding how it functions.
It's using the router to store state and such and the main cause is two dependant queries that run in parallel. I got it working again but I wouldn't mind a ticket being created to take a more in depth look into the form to see if we can pay down some tech debt on it.
```

Rather than try to focus this into smaller specific issues, this issue is to improve this page in general without changing the functionality in any way.  Note the many problems listed below and possible solutions to each.

## Acceptance Criteria
- [ ] Refactor the search page to make it simpler, more reliable, easier to understand, and easier to work on
- [ ] Do not change the user experience or functionality of the page

**Comment by esizer** [comment] 2022-05-18 14:01
## Summary

I think the large concern for this form is that we are storing the initial state in the router state which we needed to work around to avoid infinite re-renders. Another problem we are working around right now is that the pool ID is not available during the first render for some reason which forces us to run a second query right after the first so we can get the proper results.

If we take another look at the form and attempt to align it with the pattern that was adopted in the profile section, this could resolve some of the issues we are experiencing and stabilize the form.

## Important Note

I'm very late to the party on this form so these assumptions could be incorrect in regards to previous decisions made that I am un aware of. 

## Form State

I believe we were using the router state so that the back button would take the user back to a previous state. However, in all of my testing, I could not get this to work 😕 . I see two viable options, session storage and not storing form state at all.

### Possible Solutions

#### Option 1 - Session Storage

This one should be straight forward, we can simply use the new `useSessionStorage` hook to store the form state. Moving to session storage would allow us keep form state without relying on the router. This would be important since we do a have a ticket to discuss changing routers.

#### Option 2 - No State

As far as I am aware, `react-hook-form` maintains state for us. The only added benefit of using session storage would mean if the user navigated away from the page, the form would retain state.

Since keeping some sort of state within the session could be valuable I made this option 2.

### Query Issues

This one is a little trickier to handle. To be honest, I'm not really sure why this one is occurring. We have two queries, one to get the pool ID and another to get the candidates. For some reason, on the initial render of the page the pool id is not available so we simply force a second request when the pool is available, cancelling the first. My hunch is that the `urql` queries are asynchronous and the requests are being sent at the same time. 

I am less confident in providing a proposed solution for this one since `urql` makes all queries hooks which limits what we can do with them.

- Must be called in the root of a component
  - Can't be the side effect of a `useEffect()`
  - Can't be placed in an `async` function to `await` it

Also, I could be completely wrong and these could be synchronous and the issue is elsewhere 🤷

**Comment by patcon** [comment] 2022-05-26 08:56
> proposed solution for this one since urql makes all queries hooks which limits what we can do with them.

Might this be the sort of place to consider a minimal useReducer hook, since the resulting actions are more complex here?

**Comment by petertgiles** [comment] 2023-02-08 15:42
This issue is very old and pretty vague.  Our search page no longer fires a initial useless query (I think) though the state management on the page is still tricky. Brinda is working on #4716 to preserve search page state. We still use urql with hooks.  I'm tempted to close this issue in preference to smaller more targeted issues.

 @esizer @brindasasi  @patcon Thoughts on smaller more focused issues to replace this with?  Or is this issue still relevant as is?

**Comment by esizer** [comment] 2023-02-08 15:44
> Thoughts on smaller more focused issues to replace this with? Or is this issue still relevant as is?

Smaller, more targeted, issues might help but I would still love to see a refactor of that page at some point. I was working on it the last couple sprints and it is difficult to work worth at this point 😅

**Comment by petertgiles** [comment] 2023-02-08 15:52
> I would still love to see a refactor of that page at some point. I was working on it the last couple sprints and it is difficult to work worth at this point sweat_smile

Perfect, OK.  Could you list the pain points?

**Comment by esizer** [comment] 2023-02-08 16:58
> Perfect, OK. Could you list the pain points?

Yeah, so this is probably related to features being added and changed over time but, it seems to have grown to become overly complex for something that seems relatively simple.

> **Note**
> I'm not fully aware of how this form works so I may be wrong about some of this. Though, this may also be a reason why the refactor is needed. After working on this project for nearly a year, I still have no clue how this form actually works 😅 

## Possibly unnecessary code

I may be incorrect but, I don't believe we are restricting users from submitting the form anymore regardless so we should not longer need to `tryHandleSubmit` which was doing some custom logic to prevent submissions to unrelated fields. I think the only validation required now would be the 3 required fields.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/518b6ee53199eed84530f000fada366eeec9ded1/apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx#L259-L278

## Prop Drilling

We do some variable assignment at the top of the `SearchContainer` that we only use once and pass them directly to other components. We could move these to the components they are actually used in to reduce the amount of props required and declutter the parent component. For me, this just adds to confusion as to where these variables are being used especially when they are only being used once and not even in the component they are defined it :/

https://github.com/GCTC-NTGC/gc-digital-talent/blob/518b6ee53199eed84530f000fada366eeec9ded1/apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx#L232-L253

## Custom Form State

> **Note**
> This sort of relates to the prop drilling comment

We are storing the form state in a custom local state then passing it down 3 levels when it is almost identical to the form state. I feel like we could elevate the form context and simply watch the form and sync state there and acccess it through the form context. When working on the form I find myself starting at the stop `SearchContainer` and drilling down to find where exactly the state is changing making it a little chaotic.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/518b6ee53199eed84530f000fada366eeec9ded1/apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx#L397-L413

## Weird data fetching pattern

This is sort of related to the need for hooks to load data but we are first fetching the data to populate the options in the form and then using the result to fetch the candidate count. If we were able to use a `loader` we could populate the form and not need this weird waterfall of requests happening which is kind of tricky with hooks.

### Fetching Initial Data

https://github.com/GCTC-NTGC/gc-digital-talent/blob/518b6ee53199eed84530f000fada366eeec9ded1/apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx#L389-L395

### Using Initial Data to Fetch Candidate Count

https://github.com/GCTC-NTGC/gc-digital-talent/blob/518b6ee53199eed84530f000fada366eeec9ded1/apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx#L423-L431

## Multiple Components in Single File

We have the `ResultsDisplay` component defined in the same file as the `SearchContainer`. Since the search container is already fairly complex, this other component just adds clutter and it would be nice to move this to its own file.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/518b6ee53199eed84530f000fada366eeec9ded1/apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx#L92-L197

**Comment by petertgiles** [comment] 2023-02-08 17:26
@esizer wow, thanks for the detailed write-up!  I'm actually thinking that this kind of refinement would be difficult to break up into discreet tasks with specific AC.  I'm going to leave it together in this issue, I think.

**Comment by brindasasi** [comment] 2023-02-08 18:55
This is what exactly I'm struggled in this sprint. This page really have grown as a nightmare basically. 
I haven't read fully Eric's write up yet. 
 I would definitely recommend taking it on and break down the page little more.

Myself and Yoni uncovered many bugs while working to retain the state values on this page. 

I'm cleaning up what I can under my current pr. I will read the above and add my thoughts into it.  I would love a 🧠 session on this.

**Comment by petertgiles** [comment] 2023-02-08 19:12
Thanks for the confirmation, @brindasasi .  I'll put a comment on the board for retro.

**Comment by petertgiles** [comment] 2023-02-08 20:48
Retro plan: Get a good idea of the new search page before attempting this.

**Comment by mnigh** [comment] 2023-06-20 16:46
bump 
> @Jerryescandon / @gobyrne is search page going under any face lift anytime soon in your roadmap?
( If there is, we would wait on this to combine the effort or we would just do it )

**Closed** 2023-11-01 19:04 UTC
Labels: debt
