### ISSUE TITLE
Support Indigenous Self Declaration form in backend

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4976] opened 2022-12-01 15:19 UTC
# Description
We're building the Indigenous Self Declaration form (#4857), but nothing exists in the API yet to support it saving or retrieving.
We want to add fields to the User data model, in such a way that the data from the Self Declaration form could be displayed on the user profile.

Proposal for data structure:

```
enum IndigenousCommunity {
  STATUS_FIRST_NATIONS
  NON_STATUS_FIRST_NATIONS
  INUK
  METIS
  OTHER
}
enum FirstNationsStatus {
  STATUS
  NON_STATUS
}
type User/Applicant {
  indigenousCommunities: IndigenousCommunity[]
  indigenousDeclarationSignature: string
  isIndigenous: Boolean # this field already exists - maybe we replace its column in DB with an accessor, checking indigenousGroups is not null or empty? Otherwise, it would be possible to end up with inconsistencies.
}
```

**Questions**: it seems to make sense to make isIndigenous a computed field, to avoid inconsistencies (I'm part of a community but isIndigenous == false, or vice versa). However, how do we set the indigenousGroups field for existing indigenous users? Do we default them into the OTHER community, which is non-commital and could be changed by them later? Or should we just leave isIndigenous in the database for now.

# Acceptance Criteria
- [ ] Decide on data structure, add in schema (User *and* Applicant types)
- [ ] Update User.php if necessary
- [ ] Write data migration
- [ ] add fields to User factory (and seeder?)
- [ ] ensure user/applicant migrations can modify new fields (and if isIndigenous becomes a computed field, then migrations CANNOT edit it directly)
  - [ ] If isIndigenous is removed from any inputs, changes may be required in frontend, esp to the profile EE page.

**Comment by gobyrne** [comment] 2022-12-01 18:02
Duplicate of #4977

**Closed by gobyrne** 2022-12-01 18:02 UTC
Labels: feature, question
