### ISSUE TITLE
Submission Success page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3329] opened 2022-07-12 20:21 UTC
# Description

[Figma Prototype](https://www.figma.com/proto/N9NoPunkqaynjsi89Wrbh0/Direct-Intake---Poster-and-application?node-id=258%3A5045&starting-point-node-id=226%3A4567&scaling=min-zoom)

## Updated image

![image](https://user-images.githubusercontent.com/16977254/180287091-edc3e2aa-38dc-427f-82eb-db38c0a2c9e8.png)

Build the Application Success page. The only dynamic data on this page is the title of the Pool you applied to, and the id of your application. This page should be rendered at `applications/:id/thanks`,  for which we already have a stub component to populate/replace.

Tests:
- [ ] User only sees success if application is submitted and belongs to them.

**Comment by petertgiles** [comment] 2022-07-21 18:24
Will probably have to make the header and footer as part of this page.

**Comment by petertgiles** [comment] 2022-07-21 18:35
Use standard NotFound component if application was not actually submitted when user navigates to this page.

**Comment by brindasasi** [comment] 2022-08-25 15:47
We will not work on this. Upon successful submission user will be redirected to My Applications page

**Comment by gobyrne** [comment] 2022-11-08 16:13
duplicate of #2762

**Closed by gobyrne** 2022-11-08 16:13 UTC
Labels: feature
